# Generated by Django 4.2.27

from decimal import Decimal
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0002_pricehistory'),
        ('investments', '0008_dataprovider_delete_dataproviderconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquityValuation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(help_text='The asset this fundamental data belongs to', on_delete=models.CASCADE, related_name='equityvaluation_set', to='assets.asset')),
                ('report_date', models.DateField(db_index=True, help_text='The date of the report or data point')),
                ('source', models.ForeignKey(blank=True, help_text='The data provider source', null=True, on_delete=models.SET_NULL, related_name='equityvaluation_set', to='investments.dataprovider')),
                ('confidence_score', models.DecimalField(default=Decimal('1.00'), help_text='Confidence score for the data (0.01-1.00)', max_digits=3, decimal_places=2)),
                ('is_estimated', models.BooleanField(default=False, help_text='Whether this data point is estimated (not actual)')),
                ('data_quality_flags', models.JSONField(blank=True, default=list, help_text="List of quality flags")),
                ('period_type', models.CharField(choices=[('quarterly', 'Quarterly'), ('annual', 'Annual'), ('ttm', 'Trailing 12 Months'), ('mrq', 'Most Recent Quarter')], default='quarterly', help_text='Type of fiscal period', max_length=10)),
                ('fiscal_year', models.IntegerField(db_index=True, help_text='Fiscal year of the report')),
                ('fiscal_period', models.IntegerField(blank=True, help_text='Fiscal quarter (1-4) or null for annual', null=True)),
                ('period_end_date', models.DateField(blank=True, help_text='End date of the fiscal period', null=True)),
                ('is_restated', models.BooleanField(default=False, help_text='Whether this data has been restated from original filing')),
                ('original_report_date', models.DateField(blank=True, help_text='Original report date before restatement', null=True)),
                ('market_cap', models.DecimalField(blank=True, help_text='Market capitalization in USD', max_digits=20, decimal_places=2, null=True)),
                ('enterprise_value', models.DecimalField(blank=True, help_text='Enterprise value in USD', max_digits=20, decimal_places=2, null=True)),
                ('pe_ratio', models.DecimalField(blank=True, help_text='Price to Earnings ratio', max_digits=12, decimal_places=4, null=True)),
                ('pe_forward', models.DecimalField(blank=True, help_text='Forward P/E ratio', max_digits=12, decimal_places=4, null=True)),
                ('pb_ratio', models.DecimalField(blank=True, help_text='Price to Book ratio', max_digits=12, decimal_places=4, null=True)),
                ('ps_ratio', models.DecimalField(blank=True, help_text='Price to Sales ratio', max_digits=12, decimal_places=4, null=True)),
                ('ev_ebitda', models.DecimalField(blank=True, help_text='Enterprise Value to EBITDA ratio', max_digits=12, decimal_places=4, null=True)),
                ('ev_sales', models.DecimalField(blank=True, help_text='Enterprise Value to Sales ratio', max_digits=12, decimal_places=4, null=True)),
                ('peg_ratio', models.DecimalField(blank=True, help_text='PEG ratio (P/E to Growth)', max_digits=12, decimal_places=4, null=True)),
                ('dividend_yield', models.DecimalField(blank=True, help_text='Dividend yield as decimal', max_digits=10, decimal_places=4, null=True)),
                ('payout_ratio', models.DecimalField(blank=True, help_text='Dividend payout ratio as percentage', max_digits=6, decimal_places=2, null=True)),
                ('revenue_growth_yoy', models.DecimalField(blank=True, help_text='Year-over-year revenue growth as decimal', max_digits=10, decimal_places=4, null=True)),
                ('earnings_growth_yoy', models.DecimalField(blank=True, help_text='Year-over-year earnings growth as decimal', max_digits=10, decimal_places=4, null=True)),
                ('revenue_growth_3y', models.DecimalField(blank=True, help_text='3-year annual revenue growth rate as decimal', max_digits=10, decimal_places=4, null=True)),
                ('earnings_growth_3y', models.DecimalField(blank=True, help_text='3-year annual earnings growth rate as decimal', max_digits=10, decimal_places=4, null=True)),
                ('revenue_growth_5y', models.DecimalField(blank=True, help_text='5-year annual revenue growth rate as decimal', max_digits=10, decimal_places=4, null=True)),
                ('eps_growth_5y', models.DecimalField(blank=True, help_text='5-year annual EPS growth rate as decimal', max_digits=10, decimal_places=4, null=True)),
                ('gross_margin', models.DecimalField(blank=True, help_text='Gross profit margin as percentage', max_digits=8, decimal_places=4, null=True)),
                ('operating_margin', models.DecimalField(blank=True, help_text='Operating margin as percentage', max_digits=8, decimal_places=4, null=True)),
                ('net_margin', models.DecimalField(blank=True, help_text='Net profit margin as percentage', max_digits=8, decimal_places=4, null=True)),
                ('roe', models.DecimalField(blank=True, help_text='Return on Equity as decimal', max_digits=10, decimal_places=4, null=True)),
                ('roa', models.DecimalField(blank=True, help_text='Return on Assets as decimal', max_digits=10, decimal_places=4, null=True)),
                ('roic', models.DecimalField(blank=True, help_text='Return on Invested Capital as decimal', max_digits=10, decimal_places=4, null=True)),
                ('ebitda_margin', models.DecimalField(blank=True, help_text='EBITDA margin as percentage', max_digits=8, decimal_places=4, null=True)),
                ('debt_to_equity', models.DecimalField(blank=True, help_text='Debt to Equity ratio', max_digits=10, decimal_places=4, null=True)),
                ('debt_to_assets', models.DecimalField(blank=True, help_text='Debt to Assets ratio', max_digits=10, decimal_places=4, null=True)),
                ('current_ratio', models.DecimalField(blank=True, help_text='Current ratio', max_digits=8, decimal_places=4, null=True)),
                ('quick_ratio', models.DecimalField(blank=True, help_text='Quick ratio (acid test)', max_digits=8, decimal_places=4, null=True)),
                ('cash_ratio', models.DecimalField(blank=True, help_text='Cash ratio', max_digits=8, decimal_places=4, null=True)),
                ('interest_coverage', models.DecimalField(blank=True, help_text='Interest coverage ratio', max_digits=10, decimal_places=4, null=True)),
                ('equity_multiplier', models.DecimalField(blank=True, help_text='Equity multiplier', max_digits=10, decimal_places=4, null=True)),
                ('beta', models.DecimalField(blank=True, help_text='Stock beta relative to market', max_digits=8, decimal_places=4, null=True)),
                ('beta_5y', models.DecimalField(blank=True, help_text='5-year beta', max_digits=8, decimal_places=4, null=True)),
                ('wacc', models.DecimalField(blank=True, help_text='Weighted Average Cost of Capital as decimal', max_digits=8, decimal_places=4, null=True)),
                ('cost_of_equity', models.DecimalField(blank=True, help_text='Cost of equity as decimal', max_digits=8, decimal_places=4, null=True)),
                ('price_to_fcf', models.DecimalField(blank=True, help_text='Price to Free Cash Flow ratio', max_digits=12, decimal_places=4, null=True)),
                ('ev_to_revenue', models.DecimalField(blank=True, help_text='Enterprise Value to Revenue ratio', max_digits=12, decimal_places=4, null=True)),
                ('market_cap_to_revenue', models.DecimalField(blank=True, help_text='Market Cap to Revenue ratio', max_digits=12, decimal_places=4, null=True)),
                ('price_to_nav', models.DecimalField(blank=True, help_text='Price to Net Asset Value ratio', max_digits=12, decimal_places=4, null=True)),
                ('price_to_earnings_growth', models.DecimalField(blank=True, help_text='Price/Earnings to Growth ratio (PEG)', max_digits=12, decimal_places=4, null=True)),
                ('ev_to_gbv', models.DecimalField(blank=True, help_text='Enterprise Value to Gross Book Value', max_digits=12, decimal_places=4, null=True)),
                ('book_value_per_share', models.DecimalField(blank=True, help_text='Book value per share in USD', max_digits=15, decimal_places=4, null=True)),
                ('earnings_per_share', models.DecimalField(blank=True, help_text='Earnings per share (EPS) in USD', max_digits=15, decimal_places=4, null=True)),
                ('sales_per_share', models.DecimalField(blank=True, help_text='Sales per share in USD', max_digits=15, decimal_places=4, null=True)),
                ('free_cash_flow_per_share', models.DecimalField(blank=True, help_text='Free cash flow per share in USD', max_digits=15, decimal_places=4, null=True)),
                ('revenue_per_share', models.DecimalField(blank=True, help_text='Revenue per share in USD', max_digits=15, decimal_places=4, null=True)),
                ('dividend_per_share', models.DecimalField(blank=True, help_text='Annual dividend per share in USD', max_digits=12, decimal_places=4, null=True)),
                ('tangibles_book_value_per_share', models.DecimalField(blank=True, help_text='Tangible book value per share in USD', max_digits=15, decimal_places=4, null=True)),
            ],
            options={
                'db_table': 'fundamentals_equity_valuation',
                'ordering': ['-report_date'],
                'unique_together': {('asset', 'period_type', 'fiscal_year', 'fiscal_period')},
                'indexes': [
                    models.Index(fields=['asset', 'period_type', '-fiscal_year', 'fiscal_period'], name='eq_val_period_idx'),
                ],
            },
        ),
    ]
