"""
Django Management Command: Seed Countries

Seed the Country table with ISO 3166 country data.

Usage:
    python manage.py seed_countries
"""

import os
import sys
from django.core.management.base import BaseCommand
from django.db import transaction

# Add the src directory to Python path
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "../../.."))

import django

django.setup()

from assets.models.country import Country


class Command(BaseCommand):
    help = "Seed the Country table with ISO 3166 country data"

    def add_arguments(self, parser):
        parser.add_argument(
            "--clear",
            action="store_true",
            dest="clear",
            help="Clear existing countries before seeding",
        )

    def handle(self, *args, **options):
        # Clear existing data if requested
        if options.get("clear"):
            self.stdout.write(self.style.WARNING("Clearing existing countries..."))
            Country.objects.all().delete()

        # ISO 3166-1 alpha-2 country codes data
        # Data from official ISO 3166 standard
        countries_data = [
            # North America
            {
                "code": "US",
                "name": "United States",
                "alpha_3": "USA",
                "numeric_code": "840",
                "region": "Americas",
                "subregion": "Northern America",
            },
            {
                "code": "CA",
                "name": "Canada",
                "alpha_3": "CAN",
                "numeric_code": "124",
                "region": "Americas",
                "subregion": "Northern America",
            },
            {
                "code": "MX",
                "name": "Mexico",
                "alpha_3": "MEX",
                "numeric_code": "484",
                "region": "Americas",
                "subregion": "Northern America",
            },
            # Central America
            {
                "code": "GT",
                "name": "Guatemala",
                "alpha_3": "GTM",
                "numeric_code": "320",
                "region": "Americas",
                "subregion": "Central America",
            },
            {
                "code": "BZ",
                "name": "Belize",
                "alpha_3": "BLZ",
                "numeric_code": "084",
                "region": "Americas",
                "subregion": "Central America",
            },
            {
                "code": "HN",
                "name": "Honduras",
                "alpha_3": "HND",
                "numeric_code": "340",
                "region": "Americas",
                "subregion": "Central America",
            },
            {
                "code": "SV",
                "name": "El Salvador",
                "alpha_3": "SLV",
                "numeric_code": "222",
                "region": "Americas",
                "subregion": "Central America",
            },
            {
                "code": "NI",
                "name": "Nicaragua",
                "alpha_3": "NIC",
                "numeric_code": "558",
                "region": "Americas",
                "subregion": "Central America",
            },
            {
                "code": "CR",
                "name": "Costa Rica",
                "alpha_3": "CRI",
                "numeric_code": "188",
                "region": "Americas",
                "subregion": "Central America",
            },
            {
                "code": "PA",
                "name": "Panama",
                "alpha_3": "PAN",
                "numeric_code": "591",
                "region": "Americas",
                "subregion": "Central America",
            },
            # Caribbean
            {
                "code": "CU",
                "name": "Cuba",
                "alpha_3": "CUB",
                "numeric_code": "192",
                "region": "Americas",
                "subregion": "Caribbean",
            },
            {
                "code": "JM",
                "name": "Jamaica",
                "alpha_3": "JAM",
                "numeric_code": "388",
                "region": "Americas",
                "subregion": "Caribbean",
            },
            {
                "code": "HT",
                "name": "Haiti",
                "alpha_3": "HTI",
                "numeric_code": "332",
                "region": "Americas",
                "subregion": "Caribbean",
            },
            {
                "code": "DO",
                "name": "Dominican Republic",
                "alpha_3": "DOM",
                "numeric_code": "214",
                "region": "Americas",
                "subregion": "Caribbean",
            },
            {
                "code": "PR",
                "name": "Puerto Rico",
                "alpha_3": "PRI",
                "numeric_code": "630",
                "region": "Americas",
                "subregion": "Caribbean",
            },
            {
                "code": "TT",
                "name": "Trinidad and Tobago",
                "alpha_3": "TTO",
                "numeric_code": "780",
                "region": "Americas",
                "subregion": "Caribbean",
            },
            {
                "code": "BB",
                "name": "Barbados",
                "alpha_3": "BRB",
                "numeric_code": "052",
                "region": "Americas",
                "subregion": "Caribbean",
            },
            {
                "code": "BS",
                "name": "Bahamas",
                "alpha_3": "BHS",
                "numeric_code": "044",
                "region": "Americas",
                "subregion": "Caribbean",
            },
            # South America
            {
                "code": "AR",
                "name": "Argentina",
                "alpha_3": "ARG",
                "numeric_code": "032",
                "region": "Americas",
                "subregion": "South America",
            },
            {
                "code": "BR",
                "name": "Brazil",
                "alpha_3": "BRA",
                "numeric_code": "076",
                "region": "Americas",
                "subregion": "South America",
            },
            {
                "code": "CL",
                "name": "Chile",
                "alpha_3": "CHL",
                "numeric_code": "152",
                "region": "Americas",
                "subregion": "South America",
            },
            {
                "code": "CO",
                "name": "Colombia",
                "alpha_3": "COL",
                "numeric_code": "170",
                "region": "Americas",
                "subregion": "South America",
            },
            {
                "code": "PE",
                "name": "Peru",
                "alpha_3": "PER",
                "numeric_code": "604",
                "region": "Americas",
                "subregion": "South America",
            },
            {
                "code": "VE",
                "name": "Venezuela",
                "alpha_3": "VEN",
                "numeric_code": "862",
                "region": "Americas",
                "subregion": "South America",
            },
            {
                "code": "EC",
                "name": "Ecuador",
                "alpha_3": "ECU",
                "numeric_code": "218",
                "region": "Americas",
                "subregion": "South America",
            },
            {
                "code": "BO",
                "name": "Bolivia",
                "alpha_3": "BOL",
                "numeric_code": "068",
                "region": "Americas",
                "subregion": "South America",
            },
            {
                "code": "PY",
                "name": "Paraguay",
                "alpha_3": "PRY",
                "numeric_code": "600",
                "region": "Americas",
                "subregion": "South America",
            },
            {
                "code": "UY",
                "name": "Uruguay",
                "alpha_3": "URY",
                "numeric_code": "858",
                "region": "Americas",
                "subregion": "South America",
            },
            {
                "code": "GY",
                "name": "Guyana",
                "alpha_3": "GUY",
                "numeric_code": "328",
                "region": "Americas",
                "subregion": "South America",
            },
            {
                "code": "SR",
                "name": "Suriname",
                "alpha_3": "SUR",
                "numeric_code": "740",
                "region": "Americas",
                "subregion": "South America",
            },
            # Europe - Western
            {
                "code": "GB",
                "name": "United Kingdom",
                "alpha_3": "GBR",
                "numeric_code": "826",
                "region": "Europe",
                "subregion": "Western Europe",
            },
            {
                "code": "IE",
                "name": "Ireland",
                "alpha_3": "IRL",
                "numeric_code": "372",
                "region": "Europe",
                "subregion": "Western Europe",
            },
            {
                "code": "FR",
                "name": "France",
                "alpha_3": "FRA",
                "numeric_code": "250",
                "region": "Europe",
                "subregion": "Western Europe",
            },
            {
                "code": "DE",
                "name": "Germany",
                "alpha_3": "DEU",
                "numeric_code": "276",
                "region": "Europe",
                "subregion": "Western Europe",
            },
            {
                "code": "IT",
                "name": "Italy",
                "alpha_3": "ITA",
                "numeric_code": "380",
                "region": "Europe",
                "subregion": "Western Europe",
            },
            {
                "code": "ES",
                "name": "Spain",
                "alpha_3": "ESP",
                "numeric_code": "724",
                "region": "Europe",
                "subregion": "Western Europe",
            },
            {
                "code": "PT",
                "name": "Portugal",
                "alpha_3": "PRT",
                "numeric_code": "620",
                "region": "Europe",
                "subregion": "Western Europe",
            },
            {
                "code": "NL",
                "name": "Netherlands",
                "alpha_3": "NLD",
                "numeric_code": "528",
                "region": "Europe",
                "subregion": "Western Europe",
            },
            {
                "code": "BE",
                "name": "Belgium",
                "alpha_3": "BEL",
                "numeric_code": "056",
                "region": "Europe",
                "subregion": "Western Europe",
            },
            {
                "code": "LU",
                "name": "Luxembourg",
                "alpha_3": "LUX",
                "numeric_code": "442",
                "region": "Europe",
                "subregion": "Western Europe",
            },
            {
                "code": "CH",
                "name": "Switzerland",
                "alpha_3": "CHE",
                "numeric_code": "756",
                "region": "Europe",
                "subregion": "Western Europe",
            },
            {
                "code": "AT",
                "name": "Austria",
                "alpha_3": "AUT",
                "numeric_code": "040",
                "region": "Europe",
                "subregion": "Western Europe",
            },
            {
                "code": "LI",
                "name": "Liechtenstein",
                "alpha_3": "LIE",
                "numeric_code": "438",
                "region": "Europe",
                "subregion": "Western Europe",
            },
            {
                "code": "MC",
                "name": "Monaco",
                "alpha_3": "MCO",
                "numeric_code": "492",
                "region": "Europe",
                "subregion": "Western Europe",
            },
            # Europe - Northern
            {
                "code": "SE",
                "name": "Sweden",
                "alpha_3": "SWE",
                "numeric_code": "752",
                "region": "Europe",
                "subregion": "Northern Europe",
            },
            {
                "code": "NO",
                "name": "Norway",
                "alpha_3": "NOR",
                "numeric_code": "578",
                "region": "Europe",
                "subregion": "Northern Europe",
            },
            {
                "code": "DK",
                "name": "Denmark",
                "alpha_3": "DNK",
                "numeric_code": "208",
                "region": "Europe",
                "subregion": "Northern Europe",
            },
            {
                "code": "FI",
                "name": "Finland",
                "alpha_3": "FIN",
                "numeric_code": "246",
                "region": "Europe",
                "subregion": "Northern Europe",
            },
            {
                "code": "IS",
                "name": "Iceland",
                "alpha_3": "ISL",
                "numeric_code": "352",
                "region": "Europe",
                "subregion": "Northern Europe",
            },
            # Europe - Eastern
            {
                "code": "PL",
                "name": "Poland",
                "alpha_3": "POL",
                "numeric_code": "616",
                "region": "Europe",
                "subregion": "Eastern Europe",
            },
            {
                "code": "CZ",
                "name": "Czechia",
                "alpha_3": "CZE",
                "numeric_code": "203",
                "region": "Europe",
                "subregion": "Eastern Europe",
            },
            {
                "code": "HU",
                "name": "Hungary",
                "alpha_3": "HUN",
                "numeric_code": "348",
                "region": "Europe",
                "subregion": "Eastern Europe",
            },
            {
                "code": "RO",
                "name": "Romania",
                "alpha_3": "ROU",
                "numeric_code": "642",
                "region": "Europe",
                "subregion": "Eastern Europe",
            },
            {
                "code": "BG",
                "name": "Bulgaria",
                "alpha_3": "BGR",
                "numeric_code": "100",
                "region": "Europe",
                "subregion": "Eastern Europe",
            },
            {
                "code": "SK",
                "name": "Slovakia",
                "alpha_3": "SVK",
                "numeric_code": "703",
                "region": "Europe",
                "subregion": "Eastern Europe",
            },
            {
                "code": "UA",
                "name": "Ukraine",
                "alpha_3": "UKR",
                "numeric_code": "804",
                "region": "Europe",
                "subregion": "Eastern Europe",
            },
            {
                "code": "RU",
                "name": "Russia",
                "alpha_3": "RUS",
                "numeric_code": "643",
                "region": "Europe",
                "subregion": "Eastern Europe",
            },
            {
                "code": "BY",
                "name": "Belarus",
                "alpha_3": "BLR",
                "numeric_code": "112",
                "region": "Europe",
                "subregion": "Eastern Europe",
            },
            {
                "code": "LT",
                "name": "Lithuania",
                "alpha_3": "LTU",
                "numeric_code": "440",
                "region": "Europe",
                "subregion": "Northern Europe",
            },
            {
                "code": "LV",
                "name": "Latvia",
                "alpha_3": "LVA",
                "numeric_code": "428",
                "region": "Europe",
                "subregion": "Northern Europe",
            },
            {
                "code": "EE",
                "name": "Estonia",
                "alpha_3": "EST",
                "numeric_code": "233",
                "region": "Europe",
                "subregion": "Northern Europe",
            },
            # Europe - Southern
            {
                "code": "GR",
                "name": "Greece",
                "alpha_3": "GRC",
                "numeric_code": "300",
                "region": "Europe",
                "subregion": "Southern Europe",
            },
            {
                "code": "TR",
                "name": "Turkey",
                "alpha_3": "TUR",
                "numeric_code": "792",
                "region": "Asia",
                "subregion": "Western Asia",
            },
            {
                "code": "CY",
                "name": "Cyprus",
                "alpha_3": "CYP",
                "numeric_code": "196",
                "region": "Europe",
                "subregion": "Southern Europe",
            },
            {
                "code": "MT",
                "name": "Malta",
                "alpha_3": "MLT",
                "numeric_code": "470",
                "region": "Europe",
                "subregion": "Southern Europe",
            },
            {
                "code": "AL",
                "name": "Albania",
                "alpha_3": "ALB",
                "numeric_code": "008",
                "region": "Europe",
                "subregion": "Southern Europe",
            },
            {
                "code": "HR",
                "name": "Croatia",
                "alpha_3": "HRV",
                "numeric_code": "191",
                "region": "Europe",
                "subregion": "Southern Europe",
            },
            {
                "code": "SI",
                "name": "Slovenia",
                "alpha_3": "SVN",
                "numeric_code": "705",
                "region": "Europe",
                "subregion": "Southern Europe",
            },
            {
                "code": "BA",
                "name": "Bosnia and Herzegovina",
                "alpha_3": "BIH",
                "numeric_code": "070",
                "region": "Europe",
                "subregion": "Southern Europe",
            },
            {
                "code": "MK",
                "name": "North Macedonia",
                "alpha_3": "MKD",
                "numeric_code": "807",
                "region": "Europe",
                "subregion": "Southern Europe",
            },
            {
                "code": "ME",
                "name": "Montenegro",
                "alpha_3": "MNE",
                "numeric_code": "499",
                "region": "Europe",
                "subregion": "Southern Europe",
            },
            {
                "code": "RS",
                "name": "Serbia",
                "alpha_3": "SRB",
                "numeric_code": "688",
                "region": "Europe",
                "subregion": "Southern Europe",
            },
            # Asia - East
            {
                "code": "CN",
                "name": "China",
                "alpha_3": "CHN",
                "numeric_code": "156",
                "region": "Asia",
                "subregion": "Eastern Asia",
            },
            {
                "code": "JP",
                "name": "Japan",
                "alpha_3": "JPN",
                "numeric_code": "392",
                "region": "Asia",
                "subregion": "Eastern Asia",
            },
            {
                "code": "KR",
                "name": "South Korea",
                "alpha_3": "KOR",
                "numeric_code": "410",
                "region": "Asia",
                "subregion": "Eastern Asia",
            },
            {
                "code": "TW",
                "name": "Taiwan",
                "alpha_3": "TWN",
                "numeric_code": "158",
                "region": "Asia",
                "subregion": "Eastern Asia",
            },
            {
                "code": "HK",
                "name": "Hong Kong",
                "alpha_3": "HKG",
                "numeric_code": "344",
                "region": "Asia",
                "subregion": "Eastern Asia",
            },
            {
                "code": "MO",
                "name": "Macao",
                "alpha_3": "MAC",
                "numeric_code": "446",
                "region": "Asia",
                "subregion": "Eastern Asia",
            },
            {
                "code": "MN",
                "name": "Mongolia",
                "alpha_3": "MNG",
                "numeric_code": "496",
                "region": "Asia",
                "subregion": "Eastern Asia",
            },
            {
                "code": "KP",
                "name": "North Korea",
                "alpha_3": "PRK",
                "numeric_code": "408",
                "region": "Asia",
                "subregion": "Eastern Asia",
            },
            # Asia - Southeast
            {
                "code": "SG",
                "name": "Singapore",
                "alpha_3": "SGP",
                "numeric_code": "702",
                "region": "Asia",
                "subregion": "South-Eastern Asia",
            },
            {
                "code": "MY",
                "name": "Malaysia",
                "alpha_3": "MYS",
                "numeric_code": "458",
                "region": "Asia",
                "subregion": "South-Eastern Asia",
            },
            {
                "code": "TH",
                "name": "Thailand",
                "alpha_3": "THA",
                "numeric_code": "764",
                "region": "Asia",
                "subregion": "South-Eastern Asia",
            },
            {
                "code": "ID",
                "name": "Indonesia",
                "alpha_3": "IDN",
                "numeric_code": "360",
                "region": "Asia",
                "subregion": "South-Eastern Asia",
            },
            {
                "code": "PH",
                "name": "Philippines",
                "alpha_3": "PHL",
                "numeric_code": "608",
                "region": "Asia",
                "subregion": "South-Eastern Asia",
            },
            {
                "code": "VN",
                "name": "Vietnam",
                "alpha_3": "VNM",
                "numeric_code": "704",
                "region": "Asia",
                "subregion": "South-Eastern Asia",
            },
            {
                "code": "KH",
                "name": "Cambodia",
                "alpha_3": "KHM",
                "numeric_code": "116",
                "region": "Asia",
                "subregion": "South-Eastern Asia",
            },
            {
                "code": "LA",
                "name": "Laos",
                "alpha_3": "LAO",
                "numeric_code": "418",
                "region": "Asia",
                "subregion": "South-Eastern Asia",
            },
            {
                "code": "MM",
                "name": "Myanmar",
                "alpha_3": "MMR",
                "numeric_code": "104",
                "region": "Asia",
                "subregion": "South-Eastern Asia",
            },
            {
                "code": "BN",
                "name": "Brunei",
                "alpha_3": "BRN",
                "numeric_code": "096",
                "region": "Asia",
                "subregion": "South-Eastern Asia",
            },
            # Asia - South
            {
                "code": "IN",
                "name": "India",
                "alpha_3": "IND",
                "numeric_code": "356",
                "region": "Asia",
                "subregion": "Southern Asia",
            },
            {
                "code": "PK",
                "name": "Pakistan",
                "alpha_3": "PAK",
                "numeric_code": "586",
                "region": "Asia",
                "subregion": "Southern Asia",
            },
            {
                "code": "BD",
                "name": "Bangladesh",
                "alpha_3": "BGD",
                "numeric_code": "050",
                "region": "Asia",
                "subregion": "Southern Asia",
            },
            {
                "code": "LK",
                "name": "Sri Lanka",
                "alpha_3": "LKA",
                "numeric_code": "144",
                "region": "Asia",
                "subregion": "Southern Asia",
            },
            {
                "code": "NP",
                "name": "Nepal",
                "alpha_3": "NPL",
                "numeric_code": "524",
                "region": "Asia",
                "subregion": "Southern Asia",
            },
            {
                "code": "BT",
                "name": "Bhutan",
                "alpha_3": "BTN",
                "numeric_code": "064",
                "region": "Asia",
                "subregion": "Southern Asia",
            },
            {
                "code": "MV",
                "name": "Maldives",
                "alpha_3": "MDV",
                "numeric_code": "462",
                "region": "Asia",
                "subregion": "Southern Asia",
            },
            {
                "code": "AF",
                "name": "Afghanistan",
                "alpha_3": "AFG",
                "numeric_code": "004",
                "region": "Asia",
                "subregion": "Southern Asia",
            },
            # Asia - West
            {
                "code": "SA",
                "name": "Saudi Arabia",
                "alpha_3": "SAU",
                "numeric_code": "682",
                "region": "Asia",
                "subregion": "Western Asia",
            },
            {
                "code": "AE",
                "name": "United Arab Emirates",
                "alpha_3": "ARE",
                "numeric_code": "784",
                "region": "Asia",
                "subregion": "Western Asia",
            },
            {
                "code": "QA",
                "name": "Qatar",
                "alpha_3": "QAT",
                "numeric_code": "634",
                "region": "Asia",
                "subregion": "Western Asia",
            },
            {
                "code": "KW",
                "name": "Kuwait",
                "alpha_3": "KWT",
                "numeric_code": "414",
                "region": "Asia",
                "subregion": "Western Asia",
            },
            {
                "code": "BH",
                "name": "Bahrain",
                "alpha_3": "BHR",
                "numeric_code": "048",
                "region": "Asia",
                "subregion": "Western Asia",
            },
            {
                "code": "OM",
                "name": "Oman",
                "alpha_3": "OMN",
                "numeric_code": "512",
                "region": "Asia",
                "subregion": "Western Asia",
            },
            {
                "code": "IL",
                "name": "Israel",
                "alpha_3": "ISR",
                "numeric_code": "376",
                "region": "Asia",
                "subregion": "Western Asia",
            },
            {
                "code": "JO",
                "name": "Jordan",
                "alpha_3": "JOR",
                "numeric_code": "400",
                "region": "Asia",
                "subregion": "Western Asia",
            },
            {
                "code": "LB",
                "name": "Lebanon",
                "alpha_3": "LBN",
                "numeric_code": "422",
                "region": "Asia",
                "subregion": "Western Asia",
            },
            {
                "code": "SY",
                "name": "Syria",
                "alpha_3": "SYR",
                "numeric_code": "760",
                "region": "Asia",
                "subregion": "Western Asia",
            },
            {
                "code": "IQ",
                "name": "Iraq",
                "alpha_3": "IRQ",
                "numeric_code": "368",
                "region": "Asia",
                "subregion": "Western Asia",
            },
            {
                "code": "IR",
                "name": "Iran",
                "alpha_3": "IRN",
                "numeric_code": "364",
                "region": "Asia",
                "subregion": "Southern Asia",
            },
            # Asia - Central
            {
                "code": "KZ",
                "name": "Kazakhstan",
                "alpha_3": "KAZ",
                "numeric_code": "398",
                "region": "Asia",
                "subregion": "Central Asia",
            },
            {
                "code": "UZ",
                "name": "Uzbekistan",
                "alpha_3": "UZB",
                "numeric_code": "860",
                "region": "Asia",
                "subregion": "Central Asia",
            },
            {
                "code": "KG",
                "name": "Kyrgyzstan",
                "alpha_3": "KGZ",
                "numeric_code": "417",
                "region": "Asia",
                "subregion": "Central Asia",
            },
            {
                "code": "TJ",
                "name": "Tajikistan",
                "alpha_3": "TJK",
                "numeric_code": "762",
                "region": "Asia",
                "subregion": "Central Asia",
            },
            {
                "code": "TM",
                "name": "Turkmenistan",
                "alpha_3": "TKM",
                "numeric_code": "795",
                "region": "Asia",
                "subregion": "Central Asia",
            },
            # Oceania
            {
                "code": "AU",
                "name": "Australia",
                "alpha_3": "AUS",
                "numeric_code": "036",
                "region": "Oceania",
                "subregion": "Australia and New Zealand",
            },
            {
                "code": "NZ",
                "name": "New Zealand",
                "alpha_3": "NZL",
                "numeric_code": "554",
                "region": "Oceania",
                "subregion": "Australia and New Zealand",
            },
            {
                "code": "PG",
                "name": "Papua New Guinea",
                "alpha_3": "PNG",
                "numeric_code": "598",
                "region": "Oceania",
                "subregion": "Melanesia",
            },
            {
                "code": "FJ",
                "name": "Fiji",
                "alpha_3": "FJI",
                "numeric_code": "242",
                "region": "Oceania",
                "subregion": "Melanesia",
            },
            {
                "code": "SB",
                "name": "Solomon Islands",
                "alpha_3": "SLB",
                "numeric_code": "090",
                "region": "Oceania",
                "subregion": "Melanesia",
            },
            {
                "code": "VU",
                "name": "Vanuatu",
                "alpha_3": "VUT",
                "numeric_code": "548",
                "region": "Oceania",
                "subregion": "Melanesia",
            },
            {
                "code": "WS",
                "name": "Samoa",
                "alpha_3": "WSM",
                "numeric_code": "882",
                "region": "Oceania",
                "subregion": "Polynesia",
            },
            {
                "code": "TO",
                "name": "Tonga",
                "alpha_3": "TON",
                "numeric_code": "776",
                "region": "Oceania",
                "subregion": "Polynesia",
            },
            # Africa - North
            {
                "code": "EG",
                "name": "Egypt",
                "alpha_3": "EGY",
                "numeric_code": "818",
                "region": "Africa",
                "subregion": "Northern Africa",
            },
            {
                "code": "LY",
                "name": "Libya",
                "alpha_3": "LBY",
                "numeric_code": "434",
                "region": "Africa",
                "subregion": "Northern Africa",
            },
            {
                "code": "TN",
                "name": "Tunisia",
                "alpha_3": "TUN",
                "numeric_code": "788",
                "region": "Africa",
                "subregion": "Northern Africa",
            },
            {
                "code": "DZ",
                "name": "Algeria",
                "alpha_3": "DZA",
                "numeric_code": "012",
                "region": "Africa",
                "subregion": "Northern Africa",
            },
            {
                "code": "MA",
                "name": "Morocco",
                "alpha_3": "MAR",
                "numeric_code": "504",
                "region": "Africa",
                "subregion": "Northern Africa",
            },
            {
                "code": "SD",
                "name": "Sudan",
                "alpha_3": "SDN",
                "numeric_code": "729",
                "region": "Africa",
                "subregion": "Northern Africa",
            },
            # Africa - West
            {
                "code": "NG",
                "name": "Nigeria",
                "alpha_3": "NGA",
                "numeric_code": "566",
                "region": "Africa",
                "subregion": "Western Africa",
            },
            {
                "code": "GH",
                "name": "Ghana",
                "alpha_3": "GHA",
                "numeric_code": "288",
                "region": "Africa",
                "subregion": "Western Africa",
            },
            {
                "code": "CI",
                "name": "Côte d'Ivoire",
                "alpha_3": "CIV",
                "numeric_code": "384",
                "region": "Africa",
                "subregion": "Western Africa",
            },
            {
                "code": "SN",
                "name": "Senegal",
                "alpha_3": "SEN",
                "numeric_code": "686",
                "region": "Africa",
                "subregion": "Western Africa",
            },
            {
                "code": "ML",
                "name": "Mali",
                "alpha_3": "MLI",
                "numeric_code": "466",
                "region": "Africa",
                "subregion": "Western Africa",
            },
            {
                "code": "BF",
                "name": "Burkina Faso",
                "alpha_3": "BFA",
                "numeric_code": "854",
                "region": "Africa",
                "subregion": "Western Africa",
            },
            {
                "code": "NE",
                "name": "Niger",
                "alpha_3": "NER",
                "numeric_code": "562",
                "region": "Africa",
                "subregion": "Western Africa",
            },
            {
                "code": "CM",
                "name": "Cameroon",
                "alpha_3": "CMR",
                "numeric_code": "120",
                "region": "Africa",
                "subregion": "Middle Africa",
            },
            # Africa - East
            {
                "code": "KE",
                "name": "Kenya",
                "alpha_3": "KEN",
                "numeric_code": "404",
                "region": "Africa",
                "subregion": "Eastern Africa",
            },
            {
                "code": "ET",
                "name": "Ethiopia",
                "alpha_3": "ETH",
                "numeric_code": "231",
                "region": "Africa",
                "subregion": "Eastern Africa",
            },
            {
                "code": "TZ",
                "name": "Tanzania",
                "alpha_3": "TZA",
                "numeric_code": "834",
                "region": "Africa",
                "subregion": "Eastern Africa",
            },
            {
                "code": "UG",
                "name": "Uganda",
                "alpha_3": "UGA",
                "numeric_code": "800",
                "region": "Africa",
                "subregion": "Eastern Africa",
            },
            {
                "code": "RW",
                "name": "Rwanda",
                "alpha_3": "RWA",
                "numeric_code": "646",
                "region": "Africa",
                "subregion": "Eastern Africa",
            },
            {
                "code": "SO",
                "name": "Somalia",
                "alpha_3": "SOM",
                "numeric_code": "706",
                "region": "Africa",
                "subregion": "Eastern Africa",
            },
            {
                "code": "DJ",
                "name": "Djibouti",
                "alpha_3": "DJI",
                "numeric_code": "262",
                "region": "Africa",
                "subregion": "Eastern Africa",
            },
            {
                "code": "ER",
                "name": "Eritrea",
                "alpha_3": "ERI",
                "numeric_code": "232",
                "region": "Africa",
                "subregion": "Eastern Africa",
            },
            {
                "code": "MO",
                "name": "Mozambique",
                "alpha_3": "MOZ",
                "numeric_code": "508",
                "region": "Africa",
                "subregion": "Eastern Africa",
            },
            {
                "code": "ZM",
                "name": "Zambia",
                "alpha_3": "ZMB",
                "numeric_code": "894",
                "region": "Africa",
                "subregion": "Eastern Africa",
            },
            {
                "code": "ZW",
                "name": "Zimbabwe",
                "alpha_3": "ZWE",
                "numeric_code": "716",
                "region": "Africa",
                "subregion": "Eastern Africa",
            },
            {
                "code": "MW",
                "name": "Malawi",
                "alpha_3": "MWI",
                "numeric_code": "454",
                "region": "Africa",
                "subregion": "Eastern Africa",
            },
            {
                "code": "MG",
                "name": "Madagascar",
                "alpha_3": "MDG",
                "numeric_code": "450",
                "region": "Africa",
                "subregion": "Eastern Africa",
            },
            {
                "code": "MU",
                "name": "Mauritius",
                "alpha_3": "MUS",
                "numeric_code": "480",
                "region": "Africa",
                "subregion": "Eastern Africa",
            },
            # Africa - South
            {
                "code": "ZA",
                "name": "South Africa",
                "alpha_3": "ZAF",
                "numeric_code": "710",
                "region": "Africa",
                "subregion": "Southern Africa",
            },
            {
                "code": "NA",
                "name": "Namibia",
                "alpha_3": "NAM",
                "numeric_code": "516",
                "region": "Africa",
                "subregion": "Southern Africa",
            },
            {
                "code": "BW",
                "name": "Botswana",
                "alpha_3": "BWA",
                "numeric_code": "072",
                "region": "Africa",
                "subregion": "Southern Africa",
            },
            {
                "code": "LS",
                "name": "Lesotho",
                "alpha_3": "LSO",
                "numeric_code": "426",
                "region": "Africa",
                "subregion": "Southern Africa",
            },
            {
                "code": "SZ",
                "name": "Eswatini",
                "alpha_3": "SWZ",
                "numeric_code": "748",
                "region": "Africa",
                "subregion": "Southern Africa",
            },
            # Africa - Central
            {
                "code": "CD",
                "name": "DR Congo",
                "alpha_3": "COD",
                "numeric_code": "180",
                "region": "Africa",
                "subregion": "Middle Africa",
            },
            {
                "code": "CG",
                "name": "Congo",
                "alpha_3": "COG",
                "numeric_code": "178",
                "region": "Africa",
                "subregion": "Middle Africa",
            },
            {
                "code": "GA",
                "name": "Gabon",
                "alpha_3": "GAB",
                "numeric_code": "266",
                "region": "Africa",
                "subregion": "Middle Africa",
            },
            {
                "code": "AO",
                "name": "Angola",
                "alpha_3": "AGO",
                "numeric_code": "024",
                "region": "Africa",
                "subregion": "Middle Africa",
            },
            {
                "code": "CF",
                "name": "Central African Republic",
                "alpha_3": "CAF",
                "numeric_code": "140",
                "region": "Africa",
                "subregion": "Middle Africa",
            },
            {
                "code": "TD",
                "name": "Chad",
                "alpha_3": "TCD",
                "numeric_code": "148",
                "region": "Africa",
                "subregion": "Middle Africa",
            },
            {
                "code": "GQ",
                "name": "Equatorial Guinea",
                "alpha_3": "GNQ",
                "numeric_code": "226",
                "region": "Africa",
                "subregion": "Middle Africa",
            },
            # Special territories/other
            {
                "code": "AX",
                "name": "Åland Islands",
                "alpha_3": "ALA",
                "numeric_code": "248",
                "region": "Europe",
                "subregion": "Northern Europe",
            },
            {
                "code": "AS",
                "name": "American Samoa",
                "alpha_3": "ASM",
                "numeric_code": "016",
                "region": "Oceania",
                "subregion": "Polynesia",
            },
            {
                "code": "GU",
                "name": "Guam",
                "alpha_3": "GUM",
                "numeric_code": "316",
                "region": "Oceania",
                "subregion": "Micronesia",
            },
            {
                "code": "VI",
                "name": "U.S. Virgin Islands",
                "alpha_3": "VIR",
                "numeric_code": "850",
                "region": "Americas",
                "subregion": "Caribbean",
            },
            {
                "code": "PR",
                "name": "Puerto Rico",
                "alpha_3": "PRI",
                "numeric_code": "630",
                "region": "Americas",
                "subregion": "Caribbean",
            },
            {
                "code": "KY",
                "name": "Cayman Islands",
                "alpha_3": "CYM",
                "numeric_code": "136",
                "region": "Americas",
                "subregion": "Caribbean",
            },
            {
                "code": "BM",
                "name": "Bermuda",
                "alpha_3": "BMU",
                "numeric_code": "060",
                "region": "Americas",
                "subregion": "Northern America",
            },
            {
                "code": "GG",
                "name": "Guernsey",
                "alpha_3": "GGY",
                "numeric_code": "831",
                "region": "Europe",
                "subregion": "Northern Europe",
            },
            {
                "code": "IM",
                "name": "Isle of Man",
                "alpha_3": "IMN",
                "numeric_code": "833",
                "region": "Europe",
                "subregion": "Northern Europe",
            },
            {
                "code": "JE",
                "name": "Jersey",
                "alpha_3": "JEY",
                "numeric_code": "832",
                "region": "Europe",
                "subregion": "Northern Europe",
            },
            {
                "code": "FO",
                "name": "Faroe Islands",
                "alpha_3": "FRO",
                "numeric_code": "234",
                "region": "Europe",
                "subregion": "Northern Europe",
            },
            {
                "code": "GL",
                "name": "Greenland",
                "alpha_3": "GRL",
                "numeric_code": "304",
                "region": "Americas",
                "subregion": "Northern America",
            },
            {
                "code": "PR",
                "name": "Puerto Rico",
                "alpha_3": "PRI",
                "numeric_code": "630",
                "region": "Americas",
                "subregion": "Caribbean",
            },
        ]

        # Use transaction for atomic operation
        with transaction.atomic():
            # Track statistics
            created_count = 0
            updated_count = 0
            skipped_count = 0

            for country_data in countries_data:
                code = country_data["code"]

                # Check if country already exists
                country = Country.objects.filter(code=code).first()

                if country:
                    # Update existing country
                    for key, value in country_data.items():
                        if key != "code":  # Don't update the primary key
                            setattr(country, key, value)
                    country.save()
                    updated_count += 1
                else:
                    # Create new country
                    Country.objects.create(**country_data)
                    created_count += 1

            # Display results
            total_count = len(countries_data)
            self.stdout.write(
                self.style.SUCCESS(f"Successfully seeded {total_count} countries:")
            )
            self.stdout.write(f"  - Created: {created_count}")
            self.stdout.write(f"  - Updated: {updated_count}")
            self.stdout.write(
                f"  - Total: {Country.objects.count()} countries in database"
            )

            self.stdout.write(self.style.SUCCESS("✅ Countries seeded successfully!"))
