"""
Django Management Command: Seed Currencies

Seed the Currency table with ISO 4217 currency data and common cryptocurrencies.

Usage:
    python manage.py seed_currencies
"""

import os
import sys
from django.core.management.base import BaseCommand
from django.db import transaction

# Add the src directory to Python path
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "../../.."))

import django

django.setup()

from investments.models.currency import Currency
from assets.models.country import Country


class Command(BaseCommand):
    help = "Seed the Currency table with ISO 4217 and cryptocurrency data"

    def add_arguments(self, parser):
        parser.add_argument(
            "--clear",
            action="store_true",
            dest="clear",
            help="Clear existing currencies before seeding",
        )

    def handle(self, *args, **options):
        # Clear existing data if requested
        if options.get("clear"):
            self.stdout.write(self.style.WARNING("Clearing existing currencies..."))
            Currency.objects.all().delete()

        # Get country references for linking
        country_map = {
            "US": Country.objects.filter(code="US").first(),
            "CA": Country.objects.filter(code="CA").first(),
            "GB": Country.objects.filter(code="GB").first(),
            "EU": None,  # EUR is special - no single country
            "JP": Country.objects.filter(code="JP").first(),
            "CH": Country.objects.filter(code="CH").first(),
            "AU": Country.objects.filter(code="AU").first(),
            "NZ": Country.objects.filter(code="NZ").first(),
            "CN": Country.objects.filter(code="CN").first(),
            "IN": Country.objects.filter(code="IN").first(),
            "BR": Country.objects.filter(code="BR").first(),
            "MX": Country.objects.filter(code="MX").first(),
            "KR": Country.objects.filter(code="KR").first(),
            "RU": Country.objects.filter(code="RU").first(),
            "ZA": Country.objects.filter(code="ZA").first(),
            "SG": Country.objects.filter(code="SG").first(),
            "HK": Country.objects.filter(code="HK").first(),
            "NO": Country.objects.filter(code="NO").first(),
            "SE": Country.objects.filter(code="SE").first(),
            "DK": Country.objects.filter(code="DK").first(),
            "PL": Country.objects.filter(code="PL").first(),
            "TH": Country.objects.filter(code="TH").first(),
            "ID": Country.objects.filter(code="ID").first(),
            "MY": Country.objects.filter(code="MY").first(),
            "PH": Country.objects.filter(code="PH").first(),
            "VN": Country.objects.filter(code="VN").first(),
            "CZ": Country.objects.filter(code="CZ").first(),
            "HU": Country.objects.filter(code="HU").first(),
            "IL": Country.objects.filter(code="IL").first(),
            "CL": Country.objects.filter(code="CL").first(),
            "CO": Country.objects.filter(code="CO").first(),
            "PE": Country.objects.filter(code="PE").first(),
            "AR": Country.objects.filter(code="AR").first(),
            "VE": Country.objects.filter(code="VE").first(),
            "NG": Country.objects.filter(code="NG").first(),
            "EG": Country.objects.filter(code="EG").first(),
            "SA": Country.objects.filter(code="SA").first(),
            "AE": Country.objects.filter(code="AE").first(),
            "QA": Country.objects.filter(code="QA").first(),
            "KW": Country.objects.filter(code="KW").first(),
            "BH": Country.objects.filter(code="BH").first(),
            "OM": Country.objects.filter(code="OM").first(),
            "JO": Country.objects.filter(code="JO").first(),
            "LB": Country.objects.filter(code="LB").first(),
            "PK": Country.objects.filter(code="PK").first(),
            "BD": Country.objects.filter(code="BD").first(),
            "LK": Country.objects.filter(code="LK").first(),
            "NP": Country.objects.filter(code="NP").first(),
            "MV": Country.objects.filter(code="MV").first(),
            "KE": Country.objects.filter(code="KE").first(),
            "GH": Country.objects.filter(code="GH").first(),
            "TZ": Country.objects.filter(code="TZ").first(),
            "UG": Country.objects.filter(code="UG").first(),
            "ET": Country.objects.filter(code="ET").first(),
            "ZM": Country.objects.filter(code="ZM").first(),
            "ZW": Country.objects.filter(code="ZW").first(),
            "MU": Country.objects.filter(code="MU").first(),
            "NA": Country.objects.filter(code="NA").first(),
            "BW": Country.objects.filter(code="BW").first(),
            "IS": Country.objects.filter(code="IS").first(),
            "TR": Country.objects.filter(code="TR").first(),
            "RO": Country.objects.filter(code="RO").first(),
            "BG": Country.objects.filter(code="BG").first(),
            "HR": Country.objects.filter(code="HR").first(),
            "RS": Country.objects.filter(code="RS").first(),
            "UA": Country.objects.filter(code="UA").first(),
            "BY": Country.objects.filter(code="BY").first(),
            "BA": Country.objects.filter(code="BA").first(),
            "MK": Country.objects.filter(code="MK").first(),
            "ME": Country.objects.filter(code="ME").first(),
            "AL": Country.objects.filter(code="AL").first(),
            "CY": Country.objects.filter(code="CY").first(),
            "MT": Country.objects.filter(code="MT").first(),
        }

        # ISO 4217 fiat currencies data
        currencies_data = [
            # Major currencies (G10)
            {
                "code": "USD",
                "name": "United States Dollar",
                "symbol": "$",
                "numeric_code": "840",
                "is_crypto": False,
                "decimals": 2,
                "country_code": "US",
            },
            {
                "code": "EUR",
                "name": "Euro",
                "symbol": "€",
                "numeric_code": "978",
                "is_crypto": False,
                "decimals": 2,
                "country_code": "EU",
            },
            {
                "code": "JPY",
                "name": "Japanese Yen",
                "symbol": "¥",
                "numeric_code": "392",
                "is_crypto": False,
                "decimals": 0,
                "country_code": "JP",
            },
            {
                "code": "GBP",
                "name": "British Pound Sterling",
                "symbol": "£",
                "numeric_code": "826",
                "is_crypto": False,
                "decimals": 2,
                "country_code": "GB",
            },
            {
                "code": "CHF",
                "name": "Swiss Franc",
                "symbol": "Fr",
                "numeric_code": "756",
                "is_crypto": False,
                "decimals": 2,
                "country_code": "CH",
            },
            {
                "code": "CAD",
                "name": "Canadian Dollar",
                "symbol": "C$",
                "numeric_code": "124",
                "is_crypto": False,
                "decimals": 2,
                "country_code": "CA",
            },
            {
                "code": "AUD",
                "name": "Australian Dollar",
                "symbol": "A$",
                "numeric_code": "036",
                "is_crypto": False,
                "decimals": 2,
                "country_code": "AU",
            },
            {
                "code": "NZD",
                "name": "New Zealand Dollar",
                "symbol": "NZ$",
                "numeric_code": "554",
                "is_crypto": False,
                "decimals": 2,
                "country_code": "NZ",
            },
            {
                "code": "SEK",
                "name": "Swedish Krona",
                "symbol": "kr",
                "numeric_code": "752",
                "is_crypto": False,
                "decimals": 2,
                "country_code": "SE",
            },
            {
                "code": "NOK",
                "name": "Norwegian Krone",
                "symbol": "kr",
                "numeric_code": "578",
                "is_crypto": False,
                "decimals": 2,
                "country_code": "NO",
            },
            {
                "code": "DKK",
                "name": "Danish Krone",
                "symbol": "kr",
                "numeric_code": "208",
                "is_crypto": False,
                "decimals": 2,
                "country_code": "DK",
            },
            # Americas
            {
                "code": "MXN",
                "name": "Mexican Peso",
                "symbol": "$",
                "numeric_code": "484",
                "is_crypto": False,
                "decimals": 2,
                "country_code": "MX",
            },
            {
                "code": "BRL",
                "name": "Brazilian Real",
                "symbol": "R$",
                "numeric_code": "986",
                "is_crypto": False,
                "decimals": 2,
                "country_code": "BR",
            },
            {
                "code": "ARS",
                "name": "Argentine Peso",
                "symbol": "$",
                "numeric_code": "032",
                "is_crypto": False,
                "decimals": 2,
                "country_code": "AR",
            },
            {
                "code": "CLP",
                "name": "Chilean Peso",
                "symbol": "$",
                "numeric_code": "152",
                "is_crypto": False,
                "decimals": 2,
                "country_code": "CL",
            },
            {
                "code": "COP",
                "name": "Colombian Peso",
                "symbol": "$",
                "numeric_code": "170",
                "is_crypto": False,
                "decimals": 2,
                "country_code": "CO",
            },
            {
                "code": "PEN",
                "name": "Peruvian Sol",
                "symbol": "S/",
                "numeric_code": "604",
                "is_crypto": False,
                "decimals": 2,
                "country_code": "PE",
            },
            {
                "code": "VES",
                "name": "Venezuelan Bolívar",
                "symbol": "Bs.",
                "numeric_code": "928",
                "is_crypto": False,
                "decimals": 2,
                "country_code": "VE",
            },
            {
                "code": "CRC",
                "name": "Costa Rican Colón",
                "symbol": "₡",
                "numeric_code": "188",
                "is_crypto": False,
                "decimals": 2,
                "country_code": "CR",
            },
            {
                "code": "GTQ",
                "name": "Guatemalan Quetzal",
                "symbol": "Q",
                "numeric_code": "320",
                "is_crypto": False,
                "decimals": 2,
                "country_code": "GT",
            },
            # Asia-Pacific
            {
                "code": "CNY",
                "name": "Chinese Yuan",
                "symbol": "¥",
                "numeric_code": "156",
                "is_crypto": False,
                "decimals": 2,
                "country_code": "CN",
            },
            {
                "code": "HKD",
                "name": "Hong Kong Dollar",
                "symbol": "HK$",
                "numeric_code": "344",
                "is_crypto": False,
                "decimals": 2,
                "country_code": "HK",
            },
            {
                "code": "SGD",
                "name": "Singapore Dollar",
                "symbol": "S$",
                "numeric_code": "702",
                "is_crypto": False,
                "decimals": 2,
                "country_code": "SG",
            },
            {
                "code": "KRW",
                "name": "South Korean Won",
                "symbol": "₩",
                "numeric_code": "410",
                "is_crypto": False,
                "decimals": 0,
                "country_code": "KR",
            },
            {
                "code": "INR",
                "name": "Indian Rupee",
                "symbol": "₹",
                "numeric_code": "356",
                "is_crypto": False,
                "decimals": 2,
                "country_code": "IN",
            },
            {
                "code": "IDR",
                "name": "Indonesian Rupiah",
                "symbol": "Rp",
                "numeric_code": "360",
                "is_crypto": False,
                "decimals": 2,
                "country_code": "ID",
            },
            {
                "code": "MYR",
                "name": "Malaysian Ringgit",
                "symbol": "RM",
                "numeric_code": "458",
                "is_crypto": False,
                "decimals": 2,
                "country_code": "MY",
            },
            {
                "code": "PHP",
                "name": "Philippine Peso",
                "symbol": "₱",
                "numeric_code": "608",
                "is_crypto": False,
                "decimals": 2,
                "country_code": "PH",
            },
            {
                "code": "THB",
                "name": "Thai Baht",
                "symbol": "฿",
                "numeric_code": "764",
                "is_crypto": False,
                "decimals": 2,
                "country_code": "TH",
            },
            {
                "code": "VND",
                "name": "Vietnamese Dong",
                "symbol": "₫",
                "numeric_code": "704",
                "is_crypto": False,
                "decimals": 0,
                "country_code": "VN",
            },
            {
                "code": "PKR",
                "name": "Pakistani Rupee",
                "symbol": "₨",
                "numeric_code": "586",
                "is_crypto": False,
                "decimals": 2,
                "country_code": "PK",
            },
            {
                "code": "BDT",
                "name": "Bangladeshi Taka",
                "symbol": "৳",
                "numeric_code": "050",
                "is_crypto": False,
                "decimals": 2,
                "country_code": "BD",
            },
            {
                "code": "LKR",
                "name": "Sri Lankan Rupee",
                "symbol": "₨",
                "numeric_code": "144",
                "is_crypto": False,
                "decimals": 2,
                "country_code": "LK",
            },
            {
                "code": "NPR",
                "name": "Nepalese Rupee",
                "symbol": "₨",
                "numeric_code": "524",
                "is_crypto": False,
                "decimals": 2,
                "country_code": "NP",
            },
            {
                "code": "MVR",
                "name": "Maldivian Rufiyaa",
                "symbol": "Rf",
                "numeric_code": "462",
                "is_crypto": False,
                "decimals": 2,
                "country_code": "MV",
            },
            # Europe
            {
                "code": "PLN",
                "name": "Polish Złoty",
                "symbol": "zł",
                "numeric_code": "985",
                "is_crypto": False,
                "decimals": 2,
                "country_code": "PL",
            },
            {
                "code": "CZK",
                "name": "Czech Koruna",
                "symbol": "Kč",
                "numeric_code": "203",
                "is_crypto": False,
                "decimals": 2,
                "country_code": "CZ",
            },
            {
                "code": "HUF",
                "name": "Hungarian Forint",
                "symbol": "Ft",
                "numeric_code": "348",
                "is_crypto": False,
                "decimals": 2,
                "country_code": "HU",
            },
            {
                "code": "RON",
                "name": "Romanian Leu",
                "symbol": "lei",
                "numeric_code": "946",
                "is_crypto": False,
                "decimals": 2,
                "country_code": "RO",
            },
            {
                "code": "BGN",
                "name": "Bulgarian Lev",
                "symbol": "лв",
                "numeric_code": "975",
                "is_crypto": False,
                "decimals": 2,
                "country_code": "BG",
            },
            {
                "code": "HRK",
                "name": "Croatian Kuna",
                "symbol": "kn",
                "numeric_code": "191",
                "is_crypto": False,
                "decimals": 2,
                "country_code": "HR",
            },
            {
                "code": "RUB",
                "name": "Russian Ruble",
                "symbol": "₽",
                "numeric_code": "643",
                "is_crypto": False,
                "decimals": 2,
                "country_code": "RU",
            },
            {
                "code": "UAH",
                "name": "Ukrainian Hryvnia",
                "symbol": "₴",
                "numeric_code": "980",
                "is_crypto": False,
                "decimals": 2,
                "country_code": "UA",
            },
            {
                "code": "BYN",
                "name": "Belarusian Ruble",
                "symbol": "Br",
                "numeric_code": "933",
                "is_crypto": False,
                "decimals": 2,
                "country_code": "BY",
            },
            {
                "code": "RSD",
                "name": "Serbian Dinar",
                "symbol": "дин",
                "numeric_code": "941",
                "is_crypto": False,
                "decimals": 2,
                "country_code": "RS",
            },
            {
                "code": "BAM",
                "name": "Bosnia-Herzegovina Convertible Mark",
                "symbol": "КМ",
                "numeric_code": "977",
                "is_crypto": False,
                "decimals": 2,
                "country_code": "BA",
            },
            {
                "code": "MKD",
                "name": "Macedonian Denar",
                "symbol": "ден",
                "numeric_code": "807",
                "is_crypto": False,
                "decimals": 2,
                "country_code": "MK",
            },
            {
                "code": "MDL",
                "name": "Moldovan Leu",
                "symbol": "L",
                "numeric_code": "498",
                "is_crypto": False,
                "decimals": 2,
                "country_code": None,
            },
            {
                "code": "ALL",
                "name": "Albanian Lek",
                "symbol": "L",
                "numeric_code": "008",
                "is_crypto": False,
                "decimals": 2,
                "country_code": "AL",
            },
            {
                "code": "RSD",
                "name": "Serbian Dinar",
                "symbol": "дин",
                "numeric_code": "941",
                "is_crypto": False,
                "decimals": 2,
                "country_code": "RS",
            },
            {
                "code": "MAD",
                "name": "Moroccan Dirham",
                "symbol": "د.م.",
                "numeric_code": "504",
                "is_crypto": False,
                "decimals": 2,
                "country_code": "MA",
            },
            {
                "code": "TRY",
                "name": "Turkish Lira",
                "symbol": "₺",
                "numeric_code": "949",
                "is_crypto": False,
                "decimals": 2,
                "country_code": "TR",
            },
            {
                "code": "ISK",
                "name": "Icelandic Króna",
                "symbol": "kr",
                "numeric_code": "352",
                "is_crypto": False,
                "decimals": 0,
                "country_code": "IS",
            },
            {
                "code": "NIS",
                "name": "Israeli New Shekel",
                "symbol": "₪",
                "numeric_code": "376",
                "is_crypto": False,
                "decimals": 2,
                "country_code": "IL",
            },
            {
                "code": "CYP",
                "name": "Cypriot Pound",
                "symbol": "£",
                "numeric_code": "196",
                "is_crypto": False,
                "decimals": 2,
                "country_code": "CY",
            },
            {
                "code": "MTL",
                "name": "Maltese Lira",
                "symbol": "₤",
                "numeric_code": "470",
                "is_crypto": False,
                "decimals": 2,
                "country_code": "MT",
            },
            # Middle East
            {
                "code": "SAR",
                "name": "Saudi Riyal",
                "symbol": "﷼",
                "numeric_code": "682",
                "is_crypto": False,
                "decimals": 2,
                "country_code": "SA",
            },
            {
                "code": "AED",
                "name": "UAE Dirham",
                "symbol": "د.إ",
                "numeric_code": "784",
                "is_crypto": False,
                "decimals": 2,
                "country_code": "AE",
            },
            {
                "code": "QAR",
                "name": "Qatari Riyal",
                "symbol": "﷼",
                "numeric_code": "634",
                "is_crypto": False,
                "decimals": 2,
                "country_code": "QA",
            },
            {
                "code": "KWD",
                "name": "Kuwaiti Dinar",
                "symbol": "د.ك",
                "numeric_code": "414",
                "is_crypto": False,
                "decimals": 3,
                "country_code": "KW",
            },
            {
                "code": "BHD",
                "name": "Bahraini Dinar",
                "symbol": "BD",
                "numeric_code": "048",
                "is_crypto": False,
                "decimals": 3,
                "country_code": "BH",
            },
            {
                "code": "OMR",
                "name": "Omani Rial",
                "symbol": "﷼",
                "numeric_code": "512",
                "is_crypto": False,
                "decimals": 3,
                "country_code": "OM",
            },
            {
                "code": "JOD",
                "name": "Jordanian Dinar",
                "symbol": "د.ا",
                "numeric_code": "400",
                "is_crypto": False,
                "decimals": 3,
                "country_code": "JO",
            },
            {
                "code": "LBP",
                "name": "Lebanese Pound",
                "symbol": "ل.ل",
                "numeric_code": "422",
                "is_crypto": False,
                "decimals": 2,
                "country_code": "LB",
            },
            # Africa
            {
                "code": "ZAR",
                "name": "South African Rand",
                "symbol": "R",
                "numeric_code": "710",
                "is_crypto": False,
                "decimals": 2,
                "country_code": "ZA",
            },
            {
                "code": "NGN",
                "name": "Nigerian Naira",
                "symbol": "₦",
                "numeric_code": "566",
                "is_crypto": False,
                "decimals": 2,
                "country_code": "NG",
            },
            {
                "code": "EGP",
                "name": "Egyptian Pound",
                "symbol": "£",
                "numeric_code": "818",
                "is_crypto": False,
                "decimals": 2,
                "country_code": "EG",
            },
            {
                "code": "KES",
                "name": "Kenyan Shilling",
                "symbol": "KSh",
                "numeric_code": "404",
                "is_crypto": False,
                "decimals": 2,
                "country_code": "KE",
            },
            {
                "code": "GHS",
                "name": "Ghanaian Cedi",
                "symbol": "₵",
                "numeric_code": "936",
                "is_crypto": False,
                "decimals": 2,
                "country_code": "GH",
            },
            {
                "code": "TZS",
                "name": "Tanzanian Shilling",
                "symbol": "TSh",
                "numeric_code": "834",
                "is_crypto": False,
                "decimals": 2,
                "country_code": "TZ",
            },
            {
                "code": "UGX",
                "name": "Ugandan Shilling",
                "symbol": "USh",
                "numeric_code": "800",
                "is_crypto": False,
                "decimals": 0,
                "country_code": "UG",
            },
            {
                "code": "ETB",
                "name": "Ethiopian Birr",
                "symbol": "Br",
                "numeric_code": "230",
                "is_crypto": False,
                "decimals": 2,
                "country_code": "ET",
            },
            {
                "code": "ZMW",
                "name": "Zambian Kwacha",
                "symbol": "ZK",
                "numeric_code": "967",
                "is_crypto": False,
                "decimals": 2,
                "country_code": "ZM",
            },
            {
                "code": "MUR",
                "name": "Mauritian Rupee",
                "symbol": "₨",
                "numeric_code": "480",
                "is_crypto": False,
                "decimals": 2,
                "country_code": "MU",
            },
            {
                "code": "NAD",
                "name": "Namibian Dollar",
                "symbol": "N$",
                "numeric_code": "516",
                "is_crypto": False,
                "decimals": 2,
                "country_code": "NA",
            },
            {
                "code": "BWP",
                "name": "Botswanan Pula",
                "symbol": "P",
                "numeric_code": "072",
                "is_crypto": False,
                "decimals": 2,
                "country_code": "BW",
            },
        ]

        # Top cryptocurrencies by market cap
        crypto_data = [
            {
                "code": "BTC",
                "name": "Bitcoin",
                "symbol": "₿",
                "numeric_code": None,
                "is_crypto": True,
                "decimals": 8,
                "country_code": None,
            },
            {
                "code": "ETH",
                "name": "Ethereum",
                "symbol": "Ξ",
                "numeric_code": None,
                "is_crypto": True,
                "decimals": 18,
                "country_code": None,
            },
            {
                "code": "USDT",
                "name": "Tether",
                "symbol": "₮",
                "numeric_code": None,
                "is_crypto": True,
                "decimals": 6,
                "country_code": None,
            },
            {
                "code": "BNB",
                "name": "Binance Coin",
                "symbol": "BNB",
                "numeric_code": None,
                "is_crypto": True,
                "decimals": 8,
                "country_code": None,
            },
            {
                "code": "SOL",
                "name": "Solana",
                "symbol": "SOL",
                "numeric_code": None,
                "is_crypto": True,
                "decimals": 9,
                "country_code": None,
            },
            {
                "code": "XRP",
                "name": "XRP",
                "symbol": "XRP",
                "numeric_code": None,
                "is_crypto": True,
                "decimals": 6,
                "country_code": None,
            },
            {
                "code": "USDC",
                "name": "USD Coin",
                "symbol": "$",
                "numeric_code": None,
                "is_crypto": True,
                "decimals": 6,
                "country_code": None,
            },
            {
                "code": "ADA",
                "name": "Cardano",
                "symbol": "ADA",
                "numeric_code": None,
                "is_crypto": True,
                "decimals": 6,
                "country_code": None,
            },
            {
                "code": "AVAX",
                "name": "Avalanche",
                "symbol": "AVAX",
                "numeric_code": None,
                "is_crypto": True,
                "decimals": 18,
                "country_code": None,
            },
            {
                "code": "DOGE",
                "name": "Dogecoin",
                "symbol": "Ð",
                "numeric_code": None,
                "is_crypto": True,
                "decimals": 8,
                "country_code": None,
            },
            {
                "code": "DOT",
                "name": "Polkadot",
                "symbol": "DOT",
                "numeric_code": None,
                "is_crypto": True,
                "decimals": 10,
                "country_code": None,
            },
            {
                "code": "MATIC",
                "name": "Polygon",
                "symbol": "MATIC",
                "numeric_code": None,
                "is_crypto": True,
                "decimals": 18,
                "country_code": None,
            },
            {
                "code": "SHIB",
                "name": "Shiba Inu",
                "symbol": "SHIB",
                "numeric_code": None,
                "is_crypto": True,
                "decimals": 18,
                "country_code": None,
            },
            {
                "code": "TRX",
                "name": "TRON",
                "symbol": "TRX",
                "numeric_code": None,
                "is_crypto": True,
                "decimals": 6,
                "country_code": None,
            },
            {
                "code": "LTC",
                "name": "Litecoin",
                "symbol": "Ł",
                "numeric_code": None,
                "is_crypto": True,
                "decimals": 8,
                "country_code": None,
            },
            {
                "code": "LINK",
                "name": "Chainlink",
                "symbol": "LINK",
                "numeric_code": None,
                "is_crypto": True,
                "decimals": 18,
                "country_code": None,
            },
            {
                "code": "BCH",
                "name": "Bitcoin Cash",
                "symbol": "BCH",
                "numeric_code": None,
                "is_crypto": True,
                "decimals": 8,
                "country_code": None,
            },
            {
                "code": "ATOM",
                "name": "Cosmos",
                "symbol": "ATOM",
                "numeric_code": None,
                "is_crypto": True,
                "decimals": 6,
                "country_code": None,
            },
            {
                "code": "UNI",
                "name": "Uniswap",
                "symbol": "UNI",
                "numeric_code": None,
                "is_crypto": True,
                "decimals": 18,
                "country_code": None,
            },
            {
                "code": "XLM",
                "name": "Stellar",
                "symbol": "XLM",
                "numeric_code": None,
                "is_crypto": True,
                "decimals": 7,
                "country_code": None,
            },
        ]

        # Combine all currencies
        all_currencies = currencies_data + crypto_data

        # Use transaction for atomic operation
        with transaction.atomic():
            # Track statistics
            created_count = 0
            updated_count = 0

            for currency_data in all_currencies:
                code = currency_data["code"]
                country_code = currency_data.pop("country_code", None)

                # Get country object
                country = country_map.get(country_code, None) if country_code else None
                currency_data["country"] = country

                # Check if currency already exists
                currency = Currency.objects.filter(code=code).first()

                if currency:
                    # Update existing currency
                    for key, value in currency_data.items():
                        if key != "code":  # Don't update the primary key
                            setattr(currency, key, value)
                    currency.save()
                    updated_count += 1
                else:
                    # Create new currency
                    Currency.objects.create(**currency_data)
                    created_count += 1

            # Display results
            total_count = len(all_currencies)
            fiat_count = len(currencies_data)
            crypto_count = len(crypto_data)

            self.stdout.write(
                self.style.SUCCESS(f"Successfully seeded {total_count} currencies:")
            )
            self.stdout.write(f"  - Fiat: {fiat_count}")
            self.stdout.write(f"  - Crypto: {crypto_count}")
            self.stdout.write(f"  - Created: {created_count}")
            self.stdout.write(f"  - Updated: {updated_count}")
            self.stdout.write(
                f"  - Total: {Currency.objects.count()} currencies in database"
            )

            self.stdout.write(self.style.SUCCESS("✅ Currencies seeded successfully!"))
