# users/constants.py

DEFAULT_USER_STATUS_NAME = "ACTIVE"
DEFAULT_ACCOUNT_TYPE_NAME = "free"
DEFAULT_ADMIN_ROLE_NAME = "Admin"
DEFAULT_INVESTOR_ROLE_NAME = "Investor"

# Currency and formatting defaults
DEFAULT_CURRENCY = "USD"
DEFAULT_LOCALE = "en_US"
DEFAULT_TIMEZONE = "America/New_York"
DEFAULT_CACHE_TTL = 14400  # 4 hours in seconds
DEFAULT_TRADING_DAYS = 252
