# Generated by Django 4.2.27

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AITemplate",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Creation timestamp",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Last update timestamp",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Primary key",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("market_summary", "Market Summary"),
                            ("asset_analysis", "Asset Analysis"),
                            ("sector_report", "Sector Report"),
                            ("risk_commentary", "Risk Commentary"),
                            ("sentiment_summary", "Sentiment Summary"),
                            ("volatility_outlook", "Volatility Outlook"),
                            ("options_strategy", "Options Strategy"),
                            ("bond_market", "Bond Market Analysis"),
                            ("crypto_market", "Crypto Market Analysis"),
                            ("earnings_preview", "Earnings Preview"),
                            ("macro_outlook", "Macro Economic Outlook"),
                        ],
                        db_index=True,
                        help_text="Type of AI template",
                        max_length=50,
                    ),
                ),
                (
                    "symbol",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Asset symbol (null for general templates)",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "sector",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Sector name for sector-level templates",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "asset_class",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Asset class: equity, crypto, fixed_income, commodity",
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Template title for display", max_length=255
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="AI-generated content (Markdown supported)"
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        blank=True,
                        help_text="Brief summary for quick preview",
                        max_length=500,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional data: prices, metrics, model info",
                    ),
                ),
                (
                    "version",
                    models.IntegerField(
                        default=1, help_text="Version number for cache busting"
                    ),
                ),
                (
                    "last_generated_at",
                    models.DateTimeField(
                        help_text="When this template was last generated"
                    ),
                ),
                (
                    "next_refresh_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When this template should be refreshed",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this template is currently active",
                    ),
                ),
                (
                    "generation_error",
                    models.TextField(
                        blank=True,
                        help_text="Error message if generation failed",
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "ai_templates",
                "verbose_name": "AI Template",
                "verbose_name_plural": "AI Templates",
                "ordering": ["-last_generated_at"],
                "indexes": [
                    models.Index(
                        fields=["template_type", "symbol"], name="ai_template_type_idx"
                    ),
                    models.Index(
                        fields=["template_type", "sector"],
                        name="ai_template_sector_idx",
                    ),
                    models.Index(
                        fields=["template_type", "asset_class"],
                        name="ai_template_class_idx",
                    ),
                    models.Index(
                        fields=["next_refresh_at", "is_active"],
                        name="ai_template_refresh_idx",
                    ),
                    models.Index(
                        fields=["is_active", "template_type"],
                        name="ai_template_active_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=["template_type", "symbol", "sector"],
                        name="unique_template_scope",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AITemplateLog",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Creation timestamp",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Last update timestamp",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Primary key",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("market_summary", "Market Summary"),
                            ("asset_analysis", "Asset Analysis"),
                            ("sector_report", "Sector Report"),
                            ("risk_commentary", "Risk Commentary"),
                            ("sentiment_summary", "Sentiment Summary"),
                            ("volatility_outlook", "Volatility Outlook"),
                            ("options_strategy", "Options Strategy"),
                            ("bond_market", "Bond Market Analysis"),
                            ("crypto_market", "Crypto Market Analysis"),
                            ("earnings_preview", "Earnings Preview"),
                            ("macro_outlook", "Macro Economic Outlook"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("symbol", models.CharField(blank=True, max_length=20, null=True)),
                ("success", models.BooleanField(db_index=True, default=False)),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "model_used",
                    models.CharField(help_text="LLM model used", max_length=50),
                ),
                (
                    "input_tokens",
                    models.IntegerField(default=0, help_text="Tokens in prompt"),
                ),
                (
                    "output_tokens",
                    models.IntegerField(default=0, help_text="Tokens in response"),
                ),
                ("total_tokens", models.IntegerField(db_index=True, default=0)),
                (
                    "compute_time_ms",
                    models.IntegerField(
                        default=0, help_text="Generation time in milliseconds"
                    ),
                ),
                (
                    "input_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Snapshot of input data used",
                    ),
                ),
            ],
            options={
                "db_table": "ai_template_logs",
                "verbose_name": "AI Template Log",
                "verbose_name_plural": "AI Template Logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["template_type", "success"], name="ai_log_type_idx"
                    ),
                    models.Index(
                        fields=["created_at", "success"], name="ai_log_created_idx"
                    ),
                    models.Index(fields=["total_tokens"], name="ai_log_tokens_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="AIQueryLog",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Creation timestamp",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Last update timestamp",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Primary key",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "query_type",
                    models.CharField(
                        db_index=True,
                        help_text="Type of query: portfolio, market, strategy, etc.",
                        max_length=50,
                    ),
                ),
                ("query_text", models.TextField(help_text="User query or prompt")),
                ("success", models.BooleanField(db_index=True, default=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "response_text",
                    models.TextField(
                        blank=True,
                        help_text="AI response (truncated if too long)",
                        null=True,
                    ),
                ),
                ("model_used", models.CharField(max_length=50)),
                ("input_tokens", models.IntegerField(default=0)),
                ("output_tokens", models.IntegerField(default=0)),
                ("total_tokens", models.IntegerField(default=0)),
                ("compute_time_ms", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "ai_query_logs",
                "verbose_name": "AI Query Log",
                "verbose_name_plural": "AI Query Logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "query_type"], name="ai_query_user_idx"
                    ),
                    models.Index(
                        fields=["created_at", "success"], name="ai_query_created_idx"
                    ),
                    models.Index(
                        fields=["session_id", "created_at"], name="ai_query_session_idx"
                    ),
                ],
            },
        ),
    ]
