# Generated by Django 4.2.27 on 2026-01-29 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("ai_advisor", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("investments", "0016_add_options_models"),
        ("portfolios", "0002_portfolioperformance"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAIReport",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("portfolio_report", "Portfolio Report"),
                            ("holdings_analysis", "Holdings Analysis"),
                            ("performance_attribution", "Performance Attribution"),
                            ("risk_assessment", "Risk Assessment"),
                            ("rebalancing_suggestion", "Rebalancing Suggestion"),
                            ("tax_efficiency", "Tax Efficiency Analysis"),
                        ],
                        db_index=True,
                        help_text="Type of report",
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(help_text="Report title", max_length=255)),
                (
                    "content",
                    models.TextField(
                        help_text="AI-generated report content (Markdown supported)"
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        blank=True,
                        help_text="Brief summary for notifications",
                        max_length=500,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Report metrics: returns, risk, allocations, etc.",
                    ),
                ),
                (
                    "version",
                    models.IntegerField(
                        default=1, help_text="Version for cache busting"
                    ),
                ),
                (
                    "generated_at",
                    models.DateTimeField(help_text="When this report was generated"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        db_index=True, help_text="When this report expires"
                    ),
                ),
                (
                    "is_stale",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Marked stale if underlying data changed significantly",
                    ),
                ),
                (
                    "generation_error",
                    models.TextField(
                        blank=True,
                        help_text="Error message if generation failed",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "User AI Report",
                "verbose_name_plural": "User AI Reports",
                "db_table": "user_ai_reports",
                "ordering": ["-generated_at"],
            },
        ),
        migrations.RemoveIndex(
            model_name="aiquerylog",
            name="ai_query_created_idx",
        ),
        migrations.RemoveIndex(
            model_name="aiquerylog",
            name="ai_query_session_idx",
        ),
        migrations.RenameIndex(
            model_name="aitemplate",
            new_name="ai_template_templat_281876_idx",
            old_name="ai_template_type_idx",
        ),
        migrations.RenameIndex(
            model_name="aitemplate",
            new_name="ai_template_templat_f2efdf_idx",
            old_name="ai_template_sector_idx",
        ),
        migrations.RenameIndex(
            model_name="aitemplate",
            new_name="ai_template_templat_83f408_idx",
            old_name="ai_template_class_idx",
        ),
        migrations.RenameIndex(
            model_name="aitemplate",
            new_name="ai_template_next_re_9496d0_idx",
            old_name="ai_template_refresh_idx",
        ),
        migrations.RenameIndex(
            model_name="aitemplate",
            new_name="ai_template_is_acti_880e1e_idx",
            old_name="ai_template_active_idx",
        ),
        migrations.RenameIndex(
            model_name="aitemplatelog",
            new_name="ai_template_templat_be5a3d_idx",
            old_name="ai_log_type_idx",
        ),
        migrations.RenameIndex(
            model_name="aitemplatelog",
            new_name="ai_template_created_8aaa70_idx",
            old_name="ai_log_created_idx",
        ),
        migrations.RenameIndex(
            model_name="aitemplatelog",
            new_name="ai_template_total_t_29ed0d_idx",
            old_name="ai_log_tokens_idx",
        ),
        migrations.AddField(
            model_name="aiquerylog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ai_queries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="aitemplate",
            name="sector_fk",
            field=models.ForeignKey(
                blank=True,
                help_text="Sector (foreign key)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ai_templates",
                to="assets.sector",
            ),
        ),
        migrations.AddField(
            model_name="aitemplatelog",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="generation_logs",
                to="ai_advisor.aitemplate",
            ),
        ),
        migrations.AlterField(
            model_name="aiquerylog",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="aiquerylog",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="aiquerylog",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="aitemplate",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="aitemplate",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="aitemplate",
            name="sector",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="[DEPRECATED] Use sector_fk instead. Sector name for sector-level templates",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="aitemplate",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="aitemplatelog",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="aitemplatelog",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="aitemplatelog",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="useraireport",
            name="portfolio",
            field=models.ForeignKey(
                blank=True,
                help_text="Associated portfolio (if applicable)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ai_reports",
                to="portfolios.portfolio",
            ),
        ),
        migrations.AddField(
            model_name="useraireport",
            name="user",
            field=models.ForeignKey(
                help_text="Report owner",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ai_reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="useraireport",
            name="watchlist",
            field=models.ForeignKey(
                blank=True,
                help_text="Associated watchlist (if applicable)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ai_reports",
                to="investments.watchlist",
            ),
        ),
        migrations.AddIndex(
            model_name="useraireport",
            index=models.Index(
                fields=["user", "report_type"], name="user_ai_rep_user_id_f6188c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="useraireport",
            index=models.Index(
                fields=["user", "report_type", "portfolio"],
                name="user_ai_rep_user_id_5004a4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="useraireport",
            index=models.Index(
                fields=["expires_at", "is_stale"], name="user_ai_rep_expires_e91d0c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="useraireport",
            index=models.Index(
                fields=["user", "report_type", "expires_at"],
                name="user_ai_rep_user_id_30875b_idx",
            ),
        ),
    ]
