# Generated by Django 4.2.27 on 2025-12-24 20:46

from django.db import migrations, models
import django.db.models.deletion
import utils.helpers.get_defaults_user


def create_initial_data(apps, schema_editor):
    UserStatus = apps.get_model("users", "UserStatus")
    AccountType = apps.get_model("users", "AccountType")
    Role = apps.get_model("users", "Role")

    # Create default statuses with proper code
    UserStatus.objects.get_or_create(
        code="ACTIVE", defaults={"name": "active", "description": "Active account"}
    )

    # Account types (assuming no code field, or add if needed)
    AccountType.objects.get_or_create(
        name="free",
        defaults={
            "description": "Free tier",
            # add code if your model has it: "code": "FREE"
        },
    )

    # Roles
    Role.objects.get_or_create(name="Admin", defaults={"description": "Full access"})


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="account_type",
            field=models.ForeignKey(
                default=utils.helpers.get_defaults_user.get_default_account_type,
                help_text="Account type/tier",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="users",
                to="users.accounttype",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="status",
            field=models.ForeignKey(
                default=utils.helpers.get_defaults_user.get_default_user_status,
                help_text="Current account status",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="users",
                to="users.userstatus",
            ),
        ),
        migrations.RunPython(create_initial_data),
    ]
