# Generated by Django 4.2.27 on 2025-12-24 20:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('risk_level', models.PositiveSmallIntegerField(blank=True, help_text='1 (lowest) to 10 (highest)', null=True, validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'verbose_name': 'Asset Class',
                'verbose_name_plural': 'Asset Classes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('symbol_pattern', models.CharField(blank=True, help_text="e.g., '^.[A-Z]{1,5}$' for stocks", max_length=50)),
                ('asset_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='types', to='assets.assetclass')),
            ],
            options={
                'ordering': ['asset_class__name', 'name'],
                'unique_together': {('name', 'asset_class')},
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticker', models.CharField(db_index=True, max_length=30, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('isin', models.CharField(blank=True, help_text='International Securities Identification Number', max_length=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('market', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('website', models.URLField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('asset_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='assets.assettype')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
                'ordering': ['ticker'],
                'indexes': [models.Index(fields=['ticker'], name='assets_asse_ticker_22a21f_idx'), models.Index(fields=['asset_type'], name='assets_asse_asset_t_22f697_idx'), models.Index(fields=['currency'], name='assets_asse_currenc_77fc2a_idx')],
            },
        ),
    ]
