# Generated by Django 4.2.27 on 2025-12-27 00:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("investments", "0009_dataprovider_priority"),
        ("assets", "0002_pricehistory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="asset",
            name="market",
        ),
        migrations.AddField(
            model_name="asset",
            name="cusip",
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name="asset",
            name="last_price",
            field=models.DecimalField(
                blank=True, decimal_places=10, max_digits=30, null=True
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="last_price_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="asset",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="Unique URL-friendly identifier",
                max_length=200,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("delisted", "Delisted"),
                ],
                default="active",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="AssetProviderMapping",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("external_id", models.CharField(max_length=255)),
                ("is_primary_source", models.BooleanField(default=False)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provider_mappings",
                        to="assets.asset",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="investments.dataprovider",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asset Provider Mapping",
                "unique_together": {("provider", "external_id")},
            },
        ),
        migrations.CreateModel(
            name="AssetMetrics",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                (
                    "market_cap",
                    models.DecimalField(decimal_places=2, max_digits=30, null=True),
                ),
                (
                    "fdv",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Fully Diluted Valuation",
                        max_digits=30,
                        null=True,
                    ),
                ),
                (
                    "circulating_supply",
                    models.DecimalField(decimal_places=8, max_digits=40, null=True),
                ),
                (
                    "total_supply",
                    models.DecimalField(decimal_places=8, max_digits=40, null=True),
                ),
                (
                    "volume_24h",
                    models.DecimalField(decimal_places=2, max_digits=30, null=True),
                ),
                (
                    "price_change_24h",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="Percentage price change over the last 24 hours",
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "price_change_7d",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="Percentage price change over the last 7 days",
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "price_change_30d",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="Percentage price change over the last 30 days",
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "price_change_1y",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="Percentage price change over the last 1 year",
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="assets.asset",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="metrics",
                        to="investments.dataprovider",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["asset", "-date"], name="assets_asse_asset_i_d60d1d_idx"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="assetmetrics",
            constraint=models.UniqueConstraint(
                fields=("asset", "date"), name="unique_asset_metric_daily"
            ),
        ),
    ]
