# Generated by Django 4.2.27 on 2026-01-29 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_assetmetricshistoric_assetpriceshistoric_and_more'),
    ]

    operations = [
    ]
