# Generated by Django 4.2.27 on 2026-01-29 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_add_type_specific_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryptoasset',
            name='circulating_supply',
        ),
        migrations.RemoveField(
            model_name='cryptoasset',
            name='contract_address',
        ),
        migrations.RemoveField(
            model_name='cryptoasset',
            name='fdv',
        ),
        migrations.RemoveField(
            model_name='cryptoasset',
            name='max_supply',
        ),
        migrations.RemoveField(
            model_name='cryptoasset',
            name='total_supply',
        ),
        migrations.RemoveField(
            model_name='cryptoasset',
            name='tvl',
        ),
        migrations.RemoveField(
            model_name='etfasset',
            name='aum',
        ),
        migrations.RemoveField(
            model_name='etfasset',
            name='expense_ratio',
        ),
        migrations.RemoveField(
            model_name='indexasset',
            name='constituents_count',
        ),
        migrations.RemoveField(
            model_name='indexasset',
            name='weighting_method',
        ),
        migrations.RemoveField(
            model_name='stockasset',
            name='cusip',
        ),
        migrations.RemoveField(
            model_name='stockasset',
            name='dividend_yield',
        ),
        migrations.RemoveField(
            model_name='stockasset',
            name='eps',
        ),
        migrations.RemoveField(
            model_name='stockasset',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='stockasset',
            name='isin',
        ),
        migrations.RemoveField(
            model_name='stockasset',
            name='pe_ratio',
        ),
        migrations.RemoveField(
            model_name='stockasset',
            name='revenue_ttm',
        ),
        migrations.RemoveField(
            model_name='stockasset',
            name='sector',
        ),
        migrations.AddField(
            model_name='asset',
            name='aum',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Assets Under Management', max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='base_currency',
            field=models.CharField(blank=True, help_text='Base currency for forex pairs', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='circulating_supply',
            field=models.BigIntegerField(blank=True, help_text='Circulating supply (for crypto)', null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='contract_address',
            field=models.CharField(blank=True, help_text='Blockchain contract address (for crypto)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='country_of_incorporation',
            field=models.CharField(blank=True, help_text='Country for stocks', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='cusip',
            field=models.CharField(blank=True, help_text='CUSIP for US stocks', max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='dividend_yield',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Dividend yield percentage', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='eps',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Earnings per share', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='exchange',
            field=models.CharField(blank=True, help_text='Exchange name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='expense_ratio',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Expense ratio percentage', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='index_type',
            field=models.CharField(blank=True, help_text="Type of index (e.g., 'Sector Index', 'Market Index')", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='industry',
            field=models.CharField(blank=True, help_text='Industry for stocks/ETFs', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='isin',
            field=models.CharField(blank=True, help_text='International Securities Identification Number', max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='market_cap_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Market cap in USD', max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='pb_ratio',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Price-to-Book ratio', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='pe_ratio',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Price-to-Earnings ratio', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='pip_size',
            field=models.DecimalField(blank=True, decimal_places=5, help_text='PIP size', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='price_btc',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Price in BTC', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='ps_ratio',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Price-to-Sales ratio', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='quote_currency',
            field=models.CharField(blank=True, help_text='Quote currency for forex pairs', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='rebalance_frequency',
            field=models.CharField(blank=True, help_text='Rebalance frequency', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='revenue_ttm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Revenue Trailing Twelve Months', max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='sector',
            field=models.CharField(blank=True, help_text='Sector for stocks/ETFs', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='ticker_symbol',
            field=models.CharField(blank=True, help_text='Ticker symbol for stocks', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='total_supply',
            field=models.BigIntegerField(blank=True, help_text='Total supply (for crypto)', null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='underlying_tickers',
            field=models.JSONField(blank=True, default=list, help_text='Underlying assets/tickers'),
        ),
        migrations.AlterField(
            model_name='cryptoasset',
            name='blockchain',
            field=models.CharField(blank=True, help_text='Blockchain network', max_length=100, null=True),
        ),
    ]
