# Generated by Django 4.2.27 on 2026-01-29 15:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_remove_cryptoasset_circulating_supply_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text="GICS sector code (e.g., 'XLK', 'XLF')", max_length=20, unique=True)),
                ('name', models.CharField(help_text="Sector name (e.g., 'Technology', 'Financials')", max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the sector')),
                ('gics_code', models.PositiveSmallIntegerField(blank=True, help_text='GICS sector code (1-11)', null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Sector',
                'verbose_name_plural': 'Sectors',
                'db_table': 'sectors',
                'ordering': ['gics_code', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Timezone',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Timezone name (e.g., 'America/New_York')", max_length=50, unique=True)),
                ('utc_offset', models.IntegerField(help_text='UTC offset in hours (e.g., -5 for EST)')),
                ('utc_offset_str', models.CharField(help_text="UTC offset string (e.g., 'UTC-5')", max_length=10)),
                ('abbreviation', models.CharField(help_text="Timezone abbreviation (e.g., 'EST', 'PST')", max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_dst_observed', models.BooleanField(default=True, help_text='Whether Daylight Saving Time is observed')),
            ],
            options={
                'verbose_name': 'Timezone',
                'verbose_name_plural': 'Timezones',
                'db_table': 'timezones',
                'ordering': ['utc_offset', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='asset',
            name='industry',
            field=models.CharField(blank=True, help_text='[DEPRECATED] Use industry_fk instead', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='sector',
            field=models.CharField(blank=True, help_text='[DEPRECATED] Use sector_fk instead', max_length=150, null=True),
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text="Industry code (e.g., 'Semiconductors', 'Banks')", max_length=20)),
                ('name', models.CharField(help_text='Industry name', max_length=150)),
                ('gics_code', models.PositiveSmallIntegerField(blank=True, help_text='GICS industry code', null=True)),
                ('description', models.TextField(blank=True, help_text='Description of the industry')),
                ('is_active', models.BooleanField(default=True)),
                ('sector', models.ForeignKey(help_text='Parent sector', on_delete=django.db.models.deletion.CASCADE, related_name='industries', to='assets.sector')),
            ],
            options={
                'verbose_name': 'Industry',
                'verbose_name_plural': 'Industries',
                'db_table': 'industries',
                'ordering': ['sector__name', 'name'],
                'unique_together': {('sector', 'code')},
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='industry_fk',
            field=models.ForeignKey(blank=True, help_text='Industry (foreign key)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='assets.industry'),
        ),
        migrations.AddField(
            model_name='asset',
            name='sector_fk',
            field=models.ForeignKey(blank=True, help_text='Sector (foreign key)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='assets.sector'),
        ),
    ]
