# Generated by Django 4.2.27 on 2026-01-29 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_migrate_sector_industry_to_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='underlying_tickers',
            field=models.JSONField(blank=True, default=list, help_text='Underlying assets/tickers'),
        ),
    ]
