# Generated by Django 4.2.27 on 2026-01-30 14:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0010_add_user_to_ai_query_log"),
    ]

    operations = [
        migrations.AddField(
            model_name="country",
            name="alpha_3",
            field=models.CharField(blank=True, max_length=3, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="country",
            name="numeric_code",
            field=models.CharField(blank=True, max_length=3, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="country",
            name="subregion",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
