# Generated by Django 4.2.27 on 2026-01-30 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0011_country_alpha_3_country_numeric_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='mic',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='exchange',
            name='operating_hours',
            field=models.TextField(blank=True, help_text='Trading hours in JSON format'),
        ),
        migrations.AddField(
            model_name='exchange',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchanges', to='assets.country'),
        ),
    ]
