import os


NUM_WORKERS = int(os.getenv('NUM_WORKERS', '4'))
THREADS_PER_WORKER = int(os.getenv('THREADS_PER_WORKER', '1'))
PORT = int(os.getenv('ASGI_PORT', '8000'))

WEBSOCKET_CONCURRENCY = int(os.getenv('WEBSOCKET_CONCURRENCY', '1000'))

REDIS_HOST = os.getenv('REDIS_HOST', '127.0.0.1')
REDIS_PORT = int(os.getenv('REDIS_PORT', '6379'))
REDIS_PASSWORD = os.getenv('REDIS_PASSWORD', '')

WEBSOCKET_CONNECT_TIMEOUT = int(os.getenv('WEBSOCKET_CONNECT_TIMEOUT', '60'))
WEBSOCKET_PING_INTERVAL = int(os.getenv('WEBSOCKET_PING_INTERVAL', '20'))
WEBSOCKET_PING_TIMEOUT = int(os.getenv('WEBSOCKET_PING_TIMEOUT', '30'))

CHANNELS_EXPIRE_TTL = int(os.getenv('CHANNELS_EXPIRE_TTL', '86400'))

PROXY_HEADERS_COUNT = int(os.getenv('PROXY_HEADERS_COUNT', '10'))

ACCESS_LOG = os.getenv('ACCESS_LOG', '-')
