# Generated by Django 4.2.27 on 2025-12-26 13:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0007_dataproviderconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataProvider',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('api_key', models.CharField(blank=True, max_length=200)),
                ('base_url', models.URLField(blank=True)),
                ('rate_limit_per_minute', models.PositiveIntegerField(blank=True, null=True)),
                ('rate_limit_daily', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('config', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='DataProviderConfig',
        ),
    ]
