# Generated by Django 4.2.27 on 2026-01-28 19:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("investments", "0010_add_is_public_to_watchlist"),
    ]

    operations = [
        # Add db_table to Watchlist model
        migrations.AlterModelTable(
            name="watchlist",
            table="watchlists",
        ),
        # Add indexes to Watchlist model
        migrations.AddIndex(
            model_name="watchlist",
            index=models.Index(fields=["user"], name="invest_watchl_user_idx"),
        ),
        migrations.AddIndex(
            model_name="watchlist",
            index=models.Index(fields=["is_public"], name="invest_watchl_is_pub_idx"),
        ),
        migrations.AddIndex(
            model_name="watchlist",
            index=models.Index(
                fields=["user", "is_public"], name="invest_watchl_user_pub_idx"
            ),
        ),
    ]
