# Generated by Django 4.2.27 on 2026-01-28 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0010_add_watchlist_db_table'),
    ]

    operations = [
        # Add new indexes to Alert model
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['status', 'priority'], name='invest_alert_status_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['user', 'status', '-created_at'], name='invest_alert_user_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['triggered_count'], name='invest_alert_trig_cnt_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['last_triggered_at'], name='invest_alert_last_trig_idx'),
        ),
        # Add new indexes to AlertHistory model
        migrations.AddIndex(
            model_name='alerthistory',
            index=models.Index(fields=['alert', 'condition_met'], name='invest_althist_cond_idx'),
        ),
        migrations.AddIndex(
            model_name='alerthistory',
            index=models.Index(fields=['triggered_at', 'condition_met'], name='invest_althist_time_idx'),
        ),
        migrations.AddIndex(
            model_name='alerthistory',
            index=models.Index(fields=['condition_met', '-triggered_at'], name='invest_althist_cond_tm_idx'),
        ),
        # Add new indexes to AlertNotification model
        migrations.AddIndex(
            model_name='alertnotification',
            index=models.Index(fields=['status', 'sent_at'], name='invest_notif_sent_idx'),
        ),
        migrations.AddIndex(
            model_name='alertnotification',
            index=models.Index(fields=['retry_count', 'status'], name='invest_notif_retry_idx'),
        ),
    ]
