# Generated by Django 4.2.27 on 2026-01-29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("investments", "0010_add_watchlist_db_table"),
        ("users", "0002_alter_user_account_type_alter_user_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="alert",
            name="cooldown_seconds",
            field=models.IntegerField(default=300),
        ),
        migrations.AddField(
            model_name="alert",
            name="condition_operator",
            field=models.CharField(default=">=", max_length=10),
        ),
        migrations.AddField(
            model_name="alert",
            name="condition_value",
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name="alert",
            name="delivery_channels",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="alert",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="alert",
            name="last_notified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="alert",
            name="last_triggered_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="alert",
            name="name",
            field=models.CharField(default="New Alert", max_length=200),
        ),
        migrations.AddField(
            model_name="alert",
            name="priority",
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name="alert",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("paused", "Paused"),
                    ("triggered", "Triggered"),
                    ("expired", "Expired"),
                    ("deleted", "Deleted"),
                ],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="alert",
            name="symbol",
            field=models.CharField(default="AAPL", max_length=20),
        ),
        migrations.AddField(
            model_name="alert",
            name="triggered_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="alert",
            name="valid_from",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="alert",
            name="valid_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="alert",
            name="asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alerts",
                to="assets.asset",
            ),
        ),
        migrations.RemoveField(
            model_name="alert",
            name="target_value",
        ),
        migrations.RemoveField(
            model_name="alert",
            name="triggered_at",
        ),
        migrations.CreateModel(
            name="AlertHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "triggered_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("trigger_value", models.DecimalField(decimal_places=8, max_digits=20)),
                ("condition_met", models.BooleanField()),
                ("notification_sent", models.BooleanField(default=False)),
                ("notification_channels", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "alert",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="investments.alert",
                    ),
                ),
            ],
            options={
                "db_table": "investments_alert_history",
                "ordering": ["-triggered_at"],
            },
        ),
        migrations.CreateModel(
            name="AlertNotification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("channel", models.CharField(max_length=20)),
                ("status", models.CharField(default="pending", max_length=20)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("retry_count", models.IntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "alert_history",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="investments.alerthistory",
                    ),
                ),
            ],
            options={
                "db_table": "investments_alert_notification",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AlertTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("alert_type", models.CharField(max_length=50)),
                ("symbol_pattern", models.CharField(max_length=200, blank=True)),
                ("condition_template", models.JSONField()),
                ("default_value", models.DecimalField(decimal_places=8, max_digits=20)),
                ("default_priority", models.IntegerField(default=5)),
                ("default_cooldown", models.IntegerField(default=300)),
                ("default_channels", models.JSONField(default=list)),
                ("is_public", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alert_templates",
                        to="users.user",
                    ),
                ),
            ],
            options={
                "db_table": "investments_alert_template",
            },
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["status", "priority"], name="invest_alert_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["user", "status", "-created_at"], name="invest_alert_user_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["triggered_count"], name="invest_alert_trig_cnt_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["last_triggered_at"], name="invest_alert_last_trig_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alerthistory",
            index=models.Index(
                fields=["alert", "condition_met"], name="invest_althist_cond_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alerthistory",
            index=models.Index(
                fields=["triggered_at", "condition_met"], name="invest_althist_time_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alerthistory",
            index=models.Index(
                fields=["condition_met", "-triggered_at"],
                name="invest_althist_cond_tm_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="alertnotification",
            index=models.Index(
                fields=["status", "sent_at"], name="invest_notif_sent_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alertnotification",
            index=models.Index(
                fields=["retry_count", "status"], name="invest_notif_retry_idx"
            ),
        ),
    ]
