# Generated by Django 4.2.27 on 2026-01-29 14:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("assets", "0007_remove_cryptoasset_circulating_supply_and_more"),
        ("investments", "0012_alert_model_update"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsArticle",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True)),
                ("url", models.URLField(max_length=1000)),
                ("source", models.CharField(db_index=True, max_length=100)),
                ("author", models.CharField(blank=True, max_length=200)),
                ("published_at", models.DateTimeField(db_index=True)),
                (
                    "sentiment",
                    models.CharField(
                        choices=[
                            ("positive", "Positive"),
                            ("negative", "Negative"),
                            ("neutral", "Neutral"),
                        ],
                        db_index=True,
                        default="neutral",
                        max_length=20,
                    ),
                ),
                (
                    "sentiment_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="-1.0 to 1.0, negative is bearish, positive is bullish",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "related_symbols",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of ticker symbols mentioned in the article",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="News category (e.g., 'technology', 'finance')",
                        max_length=50,
                    ),
                ),
                ("image_url", models.URLField(blank=True, max_length=1000)),
                ("thumbnail_url", models.URLField(blank=True, max_length=1000)),
            ],
            options={
                "verbose_name": "News Article",
                "verbose_name_plural": "News Articles",
                "db_table": "news_articles",
                "ordering": ["-published_at"],
            },
        ),
        migrations.CreateModel(
            name="TechnicalIndicator",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "indicator_type",
                    models.CharField(
                        choices=[
                            ("sma", "Simple Moving Average"),
                            ("ema", "Exponential Moving Average"),
                            ("rsi", "Relative Strength Index"),
                            ("macd", "Moving Average Convergence Divergence"),
                            ("bb", "Bollinger Bands"),
                            ("stoch", "Stochastic Oscillator"),
                            ("adx", "Average Directional Index"),
                            ("cci", "Commodity Channel Index"),
                            ("atr", "Average True Range"),
                            ("obv", "On-Balance Volume"),
                            ("vwap", "Volume Weighted Average Price"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "timeframe",
                    models.CharField(
                        choices=[
                            ("1m", "1 Minute"),
                            ("5m", "5 Minutes"),
                            ("15m", "15 Minutes"),
                            ("30m", "30 Minutes"),
                            ("1h", "1 Hour"),
                            ("4h", "4 Hours"),
                            ("1d", "1 Day"),
                            ("1w", "1 Week"),
                            ("1M", "1 Month"),
                        ],
                        db_index=True,
                        default="1d",
                        max_length=10,
                    ),
                ),
                ("timestamp", models.DateTimeField(db_index=True)),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=10,
                        max_digits=30,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "signal",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("buy", "Buy"),
                            ("sell", "Sell"),
                            ("neutral", "Neutral"),
                            ("strong_buy", "Strong Buy"),
                            ("strong_sell", "Strong Sell"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional indicator-specific values",
                    ),
                ),
            ],
            options={
                "verbose_name": "Technical Indicator",
                "verbose_name_plural": "Technical Indicators",
                "db_table": "technical_indicators",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddField(
            model_name="technicalindicator",
            name="asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="technical_indicators",
                to="assets.asset",
            ),
        ),
        migrations.AddField(
            model_name="technicalindicator",
            name="source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="technical_indicators",
                to="investments.dataprovider",
            ),
        ),
        migrations.AddIndex(
            model_name="newsarticle",
            index=models.Index(
                fields=["published_at"], name="news_articl_publish_0977be_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="newsarticle",
            index=models.Index(fields=["source"], name="news_articl_source_8e92d3_idx"),
        ),
        migrations.AddIndex(
            model_name="newsarticle",
            index=models.Index(
                fields=["sentiment"], name="news_articl_sentime_18983e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="newsarticle",
            index=models.Index(
                fields=["category"], name="news_articl_categor_e27b88_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="newsarticle",
            index=models.Index(
                fields=["published_at", "source"], name="news_articl_publish_8a2040_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="technicalindicator",
            index=models.Index(
                fields=["asset", "indicator_type", "timestamp"],
                name="technical_i_asset_i_1c7c4a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="technicalindicator",
            index=models.Index(
                fields=["indicator_type", "timestamp"],
                name="technical_i_indicat_270d8f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="technicalindicator",
            index=models.Index(
                fields=["asset", "timeframe", "timestamp"],
                name="technical_i_asset_i_a8c40f_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="technicalindicator",
            unique_together={("asset", "indicator_type", "timeframe", "timestamp")},
        ),
    ]
