# Generated by Django 4.2.27 on 2026-01-29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0007_remove_cryptoasset_circulating_supply_and_more"),
        ("investments", "0013_add_news_and_technical_indicators"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrendingAsset",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("rank", models.IntegerField(db_index=True)),
                (
                    "market_cap",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=30, null=True
                    ),
                ),
                (
                    "volume_24h",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=30, null=True
                    ),
                ),
                (
                    "price_change_24h",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "price_change_percentage_24h",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="24h price change as percentage",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "sparkline_data",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of prices for the last 7 days",
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=models.CASCADE,
                        related_name="trending_records",
                        to="assets.asset",
                    ),
                ),
            ],
            options={
                "db_table": "trending_assets",
                "ordering": ["rank"],
                "indexes": [
                    models.Index(fields=["timestamp"], name="trending_timestamp_idx"),
                    models.Index(fields=["rank"], name="trending_rank_idx"),
                ],
            },
        ),
    ]
