# Generated by Django 4.2.27 on 2026-01-29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0007_remove_cryptoasset_circulating_supply_and_more"),
        ("investments", "0014_add_trending_assets"),
    ]

    operations = [
        migrations.CreateModel(
            name="DEXTradingPair",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "dex_name",
                    models.CharField(
                        db_index=True,
                        help_text="DEX name (e.g., Uniswap, SushiSwap, PancakeSwap)",
                        max_length=100,
                    ),
                ),
                (
                    "pool_address",
                    models.CharField(
                        help_text="Contract address of the liquidity pool",
                        max_length=255,
                    ),
                ),
                (
                    "reserve_base",
                    models.DecimalField(
                        blank=True, decimal_places=18, max_digits=30, null=True
                    ),
                ),
                (
                    "reserve_quote",
                    models.DecimalField(
                        blank=True, decimal_places=18, max_digits=30, null=True
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=18, max_digits=30, null=True
                    ),
                ),
                (
                    "volume_24h",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=30, null=True
                    ),
                ),
                (
                    "volume_24h_base",
                    models.DecimalField(
                        blank=True, decimal_places=18, max_digits=30, null=True
                    ),
                ),
                (
                    "liquidity_usd",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=30, null=True
                    ),
                ),
                (
                    "fee_percentage",
                    models.DecimalField(
                        decimal_places=3,
                        default=0.003,
                        help_text="Trading fee percentage (e.g., 0.003 for 0.3%)",
                        max_digits=5,
                    ),
                ),
                (
                    "token_0_address",
                    models.CharField(
                        blank=True,
                        help_text="Token 0 contract address",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "token_1_address",
                    models.CharField(
                        blank=True,
                        help_text="Token 1 contract address",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this trading pair is currently active",
                    ),
                ),
                (
                    "last_synced_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time data was synced from the DEX",
                        null=True,
                    ),
                ),
                (
                    "base_asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dex_base_pairs",
                        to="assets.asset",
                    ),
                ),
                (
                    "quote_asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dex_quote_pairs",
                        to="assets.asset",
                    ),
                ),
            ],
            options={
                "db_table": "dex_trading_pairs",
                "indexes": [
                    models.Index(fields=["dex_name"], name="dex_trading_dex_name_idx"),
                    models.Index(
                        fields=["base_asset", "quote_asset"],
                        name="dex_trading_base_quote_idx",
                    ),
                    models.Index(
                        fields=["is_active"], name="dex_trading_is_active_idx"
                    ),
                    models.Index(
                        fields=["liquidity_usd"], name="dex_trading_liq_usd_idx"
                    ),
                ],
                "unique_together": {("dex_name", "pool_address")},
            },
        ),
    ]
