# Generated by Django 4.2.27 on 2026-01-29

from django.db import migrations, models
import django.db.models.deletion
import django.core.validators
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0007_remove_cryptoasset_circulating_supply_and_more"),
        ("investments", "0015_add_dex_trading_pairs"),
    ]

    operations = [
        migrations.CreateModel(
            name="OptionContract",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "option_symbol",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                ("ticker", models.CharField(db_index=True, max_length=20)),
                ("underlying_symbol", models.CharField(db_index=True, max_length=10)),
                ("expiry_date", models.DateField(db_index=True)),
                (
                    "option_type",
                    models.CharField(
                        choices=[("C", "Call"), ("P", "Put")],
                        db_index=True,
                        max_length=1,
                    ),
                ),
                (
                    "strike_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "contract_size",
                    models.IntegerField(
                        default=100,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "exercise_style",
                    models.CharField(
                        choices=[
                            ("american", "American"),
                            ("european", "European"),
                            ("bermuda", "Bermuda"),
                        ],
                        default="american",
                        max_length=20,
                    ),
                ),
                (
                    "settlement_type",
                    models.CharField(
                        choices=[("cash", "Cash"), ("physical", "Physical")],
                        default="physical",
                        max_length=20,
                    ),
                ),
                ("is_standard", models.BooleanField(db_index=True, default=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("last_trade_date", models.DateTimeField(blank=True, null=True)),
                (
                    "last_price",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "bid",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                ("bid_size", models.IntegerField(blank=True, null=True)),
                (
                    "ask",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                ("ask_size", models.IntegerField(blank=True, null=True)),
                (
                    "bid_ask_spread",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                ("volume", models.BigIntegerField(blank=True, null=True)),
                ("open_interest", models.BigIntegerField(blank=True, null=True)),
                ("open_interest_change", models.BigIntegerField(blank=True, null=True)),
                (
                    "implied_volatility",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=8,
                        null=True,
                        validators=[
                            django.core.validators.MaxValueValidator(Decimal("5.0"))
                        ],
                    ),
                ),
                (
                    "delta",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=8,
                        null=True,
                        validators=[
                            django.core.validators.MinValue(Decimal("-1.0")),
                            django.core.validators.MaxValue(Decimal("1.0")),
                        ],
                    ),
                ),
                (
                    "gamma",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValue(Decimal("0"))],
                    ),
                ),
                (
                    "theta",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "vega",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "rho",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValue(Decimal("-1.0")),
                            django.core.validators.MaxValue(Decimal("1.0")),
                        ],
                    ),
                ),
                (
                    "intrinsic_value",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "extrinsic_value",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "theoretical_value",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "break_even",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("days_to_expiration", models.IntegerField(blank=True, null=True)),
                (
                    "time_value",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "put_call_ratio",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=8, null=True
                    ),
                ),
                (
                    "vwap",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "premium",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "change",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "change_percent",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=8, null=True
                    ),
                ),
                (
                    "high",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "low",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "open",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "close",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "settlement_price",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "previous_close",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "tick_size",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.01"), max_digits=6
                    ),
                ),
                ("exchange", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "primary_exchange",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "market_status",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("fetched_at", models.DateTimeField(auto_now=True)),
                (
                    "underlying_asset",
                    models.ForeignKey(
                        db_index=True,
                        help_text="Underlying asset for this option",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="option_contracts",
                        to="assets.asset",
                    ),
                ),
            ],
            options={
                "db_table": "option_contracts",
                "ordering": ["-volume", "-open_interest"],
                "indexes": [
                    models.Index(fields=["underlying_symbol", "expiry_date"]),
                    models.Index(
                        fields=["underlying_symbol", "option_type", "strike_price"]
                    ),
                    models.Index(
                        fields=["underlying_symbol", "expiry_date", "option_type"]
                    ),
                    models.Index(fields=["implied_volatility"]),
                    models.Index(fields=["delta"]),
                    models.Index(fields=["theta"]),
                    models.Index(fields=["volume"]),
                    models.Index(fields=["open_interest"]),
                    models.Index(fields=["is_active", "is_standard"]),
                ],
                "verbose_name": "Option Contract",
                "verbose_name_plural": "Option Contracts",
            },
        ),
        migrations.CreateModel(
            name="OptionsContractSnapshot",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("trade_date", models.DateField(db_index=True)),
                (
                    "open",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "high",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "low",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "close",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                ("volume", models.BigIntegerField(blank=True, null=True)),
                ("open_interest", models.BigIntegerField(blank=True, null=True)),
                (
                    "implied_volatility",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=8, null=True
                    ),
                ),
                (
                    "delta",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=8, null=True
                    ),
                ),
                (
                    "gamma",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                (
                    "theta",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "vega",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "rho",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="investments.optioncontract",
                    ),
                ),
            ],
            options={
                "db_table": "options_contract_snapshots",
                "ordering": ["-trade_date"],
                "indexes": [
                    models.Index(fields=["contract", "trade_date"]),
                    models.Index(fields=["trade_date", "implied_volatility"]),
                ],
                "verbose_name": "Options Contract Snapshot",
                "verbose_name_plural": "Options Contract Snapshots",
            },
        ),
        migrations.CreateModel(
            name="OptionsGreeksHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("timestamp", models.DateTimeField(db_index=True)),
                (
                    "delta",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=8, null=True
                    ),
                ),
                (
                    "gamma",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                (
                    "theta",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "vega",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "rho",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "implied_volatility",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=8, null=True
                    ),
                ),
                (
                    "theoretical_value",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "underlying_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "risk_free_rate",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=6, null=True
                    ),
                ),
                (
                    "days_to_expiration",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=8, null=True
                    ),
                ),
                (
                    "time_to_expiration",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=8, null=True
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="greeks_history",
                        to="investments.optioncontract",
                    ),
                ),
            ],
            options={
                "db_table": "options_greeks_history",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(fields=["contract", "timestamp"]),
                    models.Index(fields=["timestamp", "delta"]),
                ],
                "verbose_name": "Options Greeks History",
                "verbose_name_plural": "Options Greeks History",
            },
        ),
    ]
