# Generated by Django 4.2.27 on 2026-01-29 16:11

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0009_migrate_sector_industry_to_fk"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("investments", "0015_add_dex_trading_pairs"),
    ]

    operations = [
        migrations.CreateModel(
            name="APIKey",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("key_value", models.CharField(max_length=500)),
                (
                    "key_type",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("basic", "Basic"),
                            ("pro", "Pro"),
                            ("enterprise", "Enterprise"),
                        ],
                        default="free",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("rate_limited", "Rate Limited"),
                            ("disabled", "Disabled"),
                            ("expired", "Expired"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "rate_limit_per_minute",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "rate_limit_daily",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        default=10,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("usage_today", models.PositiveIntegerField(default=0)),
                ("usage_today_reset", models.DateTimeField(auto_now_add=True)),
                ("usage_this_hour", models.PositiveIntegerField(default=0)),
                ("usage_this_hour_reset", models.DateTimeField(auto_now_add=True)),
                ("total_usage_lifetime", models.PositiveBigIntegerField(default=0)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("last_success_at", models.DateTimeField(blank=True, null=True)),
                ("last_failure_at", models.DateTimeField(blank=True, null=True)),
                ("consecutive_failures", models.PositiveSmallIntegerField(default=0)),
                (
                    "auto_recover_after_minutes",
                    models.PositiveSmallIntegerField(default=60),
                ),
                (
                    "max_consecutive_failures",
                    models.PositiveSmallIntegerField(default=5),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "db_table": "api_keys",
                "ordering": ["provider", "priority", "id"],
            },
        ),
        migrations.CreateModel(
            name="APIKeyUsageLog",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("endpoint", models.CharField(max_length=200)),
                ("method", models.CharField(default="GET", max_length=10)),
                ("status_code", models.PositiveIntegerField()),
                ("success", models.BooleanField()),
                ("response_time_ms", models.PositiveIntegerField()),
                ("error_type", models.CharField(blank=True, max_length=100)),
                ("error_message", models.TextField(blank=True)),
                ("request_params", models.JSONField(blank=True, default=dict)),
                (
                    "response_size_bytes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
            ],
            options={
                "db_table": "api_key_usage_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OptionContract",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "option_symbol",
                    models.CharField(
                        db_index=True,
                        help_text="Full option symbol (e.g., O:AAPL230120C00150000)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "ticker",
                    models.CharField(
                        db_index=True,
                        help_text="Option ticker without O: prefix",
                        max_length=20,
                    ),
                ),
                (
                    "underlying_symbol",
                    models.CharField(
                        db_index=True,
                        help_text="Underlying stock symbol (e.g., AAPL)",
                        max_length=10,
                    ),
                ),
                (
                    "expiry_date",
                    models.DateField(db_index=True, help_text="Option expiration date"),
                ),
                (
                    "option_type",
                    models.CharField(
                        choices=[("C", "Call"), ("P", "Put")],
                        db_index=True,
                        help_text="C for Call, P for Put",
                        max_length=1,
                    ),
                ),
                (
                    "strike_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Strike price in USD",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "contract_size",
                    models.IntegerField(
                        default=100,
                        help_text="Number of shares per contract (usually 100)",
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("1"))
                        ],
                    ),
                ),
                (
                    "exercise_style",
                    models.CharField(
                        choices=[
                            ("american", "American"),
                            ("european", "European"),
                            ("bermuda", "Bermuda"),
                        ],
                        default="american",
                        help_text="Exercise style (American, European, Bermuda)",
                        max_length=20,
                    ),
                ),
                (
                    "settlement_type",
                    models.CharField(
                        choices=[("cash", "Cash"), ("physical", "Physical")],
                        default="physical",
                        help_text="Settlement type",
                        max_length=20,
                    ),
                ),
                (
                    "is_standard",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this is a standard contract (non-leveraged, non-mini)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this contract is currently tradeable",
                    ),
                ),
                (
                    "last_trade_date",
                    models.DateTimeField(
                        blank=True, help_text="Last trade timestamp", null=True
                    ),
                ),
                (
                    "last_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Last traded price",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "bid",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Current bid price",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "bid_size",
                    models.IntegerField(
                        blank=True,
                        help_text="Bid size (number of contracts)",
                        null=True,
                    ),
                ),
                (
                    "ask",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Current ask price",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "ask_size",
                    models.IntegerField(
                        blank=True,
                        help_text="Ask size (number of contracts)",
                        null=True,
                    ),
                ),
                (
                    "bid_ask_spread",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Bid-ask spread",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "volume",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Trading volume (number of contracts)",
                        null=True,
                    ),
                ),
                (
                    "open_interest",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Open interest (number of open contracts)",
                        null=True,
                    ),
                ),
                (
                    "open_interest_change",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Change in open interest from previous day",
                        null=True,
                    ),
                ),
                (
                    "implied_volatility",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Implied volatility as decimal (e.g., 0.25 for 25%)",
                        max_digits=8,
                        null=True,
                        validators=[
                            django.core.validators.MaxValueValidator(Decimal("5.0"))
                        ],
                    ),
                ),
                (
                    "delta",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Delta - price change per $1 move in underlying",
                        max_digits=8,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("-1.0")),
                            django.core.validators.MaxValueValidator(Decimal("1.0")),
                        ],
                    ),
                ),
                (
                    "gamma",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Gamma - delta change per $1 move in underlying",
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "theta",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Theta - time decay per day in dollars",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "vega",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Vega - price change per 1% change in IV",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "rho",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Rho - sensitivity to interest rates",
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("-1.0")),
                            django.core.validators.MaxValueValidator(Decimal("1.0")),
                        ],
                    ),
                ),
                (
                    "intrinsic_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Intrinsic value (in-the-money amount)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "extrinsic_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Extrinsic value (time value)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "theoretical_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Theoretical/model value",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "break_even",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Break-even price at expiration",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "days_to_expiration",
                    models.IntegerField(
                        blank=True, help_text="Days until expiration", null=True
                    ),
                ),
                (
                    "time_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Time value as percentage",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "put_call_ratio",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Put/Call volume ratio for this expiration",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "vwap",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Volume-weighted average price",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "premium",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Total premium (price * contract_size * 100)",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "change",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Price change from previous close",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "change_percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Price change percentage",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "high",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="High price of the day",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "low",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Low price of the day",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "open",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Opening price",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "close",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Closing price",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "settlement_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Settlement price (end of day)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "previous_close",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Previous day's closing price",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "tick_size",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.01"),
                        help_text="Minimum price increment",
                        max_digits=6,
                    ),
                ),
                (
                    "exchange",
                    models.CharField(
                        blank=True,
                        help_text="Primary exchange where option trades",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "primary_exchange",
                    models.CharField(
                        blank=True,
                        help_text="Primary exchange code",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "market_status",
                    models.CharField(
                        blank=True,
                        help_text="Market status (open, closed, pre-market, after-hours)",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "fetched_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Last time data was fetched from Polygon.io",
                    ),
                ),
            ],
            options={
                "verbose_name": "Option Contract",
                "verbose_name_plural": "Option Contracts",
                "db_table": "option_contracts",
                "ordering": ["-volume", "-open_interest"],
            },
        ),
        migrations.CreateModel(
            name="OptionsContractSnapshot",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "trade_date",
                    models.DateField(db_index=True, help_text="Date of the snapshot"),
                ),
                (
                    "open",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Opening price",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "high",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="High price of the day",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "low",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Low price of the day",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "close",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Closing price",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "volume",
                    models.BigIntegerField(
                        blank=True, help_text="Trading volume", null=True
                    ),
                ),
                (
                    "open_interest",
                    models.BigIntegerField(
                        blank=True, help_text="Open interest at end of day", null=True
                    ),
                ),
                (
                    "implied_volatility",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Implied volatility",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "delta",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=8, null=True
                    ),
                ),
                (
                    "gamma",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                (
                    "theta",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "vega",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "rho",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Options Contract Snapshot",
                "verbose_name_plural": "Options Contract Snapshots",
                "db_table": "options_contract_snapshots",
                "ordering": ["-trade_date"],
            },
        ),
        migrations.CreateModel(
            name="OptionsGreeksHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, help_text="Timestamp of the Greeks calculation"
                    ),
                ),
                (
                    "delta",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=8, null=True
                    ),
                ),
                (
                    "gamma",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                (
                    "theta",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "vega",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "rho",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "implied_volatility",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=8, null=True
                    ),
                ),
                (
                    "theoretical_value",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "underlying_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Underlying asset price at time of calculation",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "risk_free_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Risk-free rate used in calculation",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "days_to_expiration",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=8, null=True
                    ),
                ),
                (
                    "time_to_expiration",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Time to expiration in years",
                        max_digits=8,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Options Greeks History",
                "verbose_name_plural": "Options Greeks History",
                "db_table": "options_greeks_history",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AlterModelOptions(
            name="alert",
            options={"ordering": ["-priority", "-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="dextradingpair",
            options={
                "verbose_name": "DEX Trading Pair",
                "verbose_name_plural": "DEX Trading Pairs",
            },
        ),
        migrations.AlterModelOptions(
            name="trendingasset",
            options={
                "ordering": ["rank"],
                "verbose_name": "Trending Asset",
                "verbose_name_plural": "Trending Assets",
            },
        ),
        migrations.AlterModelOptions(
            name="watchlist",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RenameIndex(
            model_name="alert",
            new_name="investments_status_101e9c_idx",
            old_name="invest_alert_status_idx",
        ),
        migrations.RenameIndex(
            model_name="alert",
            new_name="investments_user_id_60abc2_idx",
            old_name="invest_alert_user_idx",
        ),
        migrations.RenameIndex(
            model_name="alert",
            new_name="investments_trigger_e5bdb9_idx",
            old_name="invest_alert_trig_cnt_idx",
        ),
        migrations.RenameIndex(
            model_name="alert",
            new_name="investments_last_tr_f6394d_idx",
            old_name="invest_alert_last_trig_idx",
        ),
        migrations.RenameIndex(
            model_name="alerthistory",
            new_name="investments_alert_i_f7c8ca_idx",
            old_name="invest_althist_cond_idx",
        ),
        migrations.RenameIndex(
            model_name="alerthistory",
            new_name="investments_trigger_16bc25_idx",
            old_name="invest_althist_time_idx",
        ),
        migrations.RenameIndex(
            model_name="alerthistory",
            new_name="investments_conditi_094781_idx",
            old_name="invest_althist_cond_tm_idx",
        ),
        migrations.RenameIndex(
            model_name="alertnotification",
            new_name="investments_status_c640ce_idx",
            old_name="invest_notif_sent_idx",
        ),
        migrations.RenameIndex(
            model_name="alertnotification",
            new_name="investments_retry_c_e74b7e_idx",
            old_name="invest_notif_retry_idx",
        ),
        migrations.RenameIndex(
            model_name="dextradingpair",
            new_name="dex_trading_dex_nam_532165_idx",
            old_name="dex_trading_dex_name_idx",
        ),
        migrations.RenameIndex(
            model_name="dextradingpair",
            new_name="dex_trading_base_as_492625_idx",
            old_name="dex_trading_base_quote_idx",
        ),
        migrations.RenameIndex(
            model_name="dextradingpair",
            new_name="dex_trading_is_acti_0cf26f_idx",
            old_name="dex_trading_is_active_idx",
        ),
        migrations.RenameIndex(
            model_name="dextradingpair",
            new_name="dex_trading_liquidi_d730f9_idx",
            old_name="dex_trading_liq_usd_idx",
        ),
        migrations.RenameIndex(
            model_name="trendingasset",
            new_name="trending_as_timesta_16fcc8_idx",
            old_name="trending_timestamp_idx",
        ),
        migrations.RenameIndex(
            model_name="trendingasset",
            new_name="trending_as_rank_9b8c9e_idx",
            old_name="trending_rank_idx",
        ),
        migrations.RenameIndex(
            model_name="watchlist",
            new_name="watchlists_user_id_ef6223_idx",
            old_name="invest_watchl_user_idx",
        ),
        migrations.RenameIndex(
            model_name="watchlist",
            new_name="watchlists_is_publ_3db477_idx",
            old_name="invest_watchl_is_pub_idx",
        ),
        migrations.RenameIndex(
            model_name="watchlist",
            new_name="watchlists_user_id_027a76_idx",
            old_name="invest_watchl_user_pub_idx",
        ),
        migrations.RemoveField(
            model_name="alert",
            name="asset",
        ),
        migrations.RemoveField(
            model_name="alert",
            name="is_active",
        ),
        migrations.AlterField(
            model_name="alert",
            name="alert_type",
            field=models.CharField(
                choices=[
                    ("price_above", "Price Above"),
                    ("price_below", "Price Below"),
                    ("percentage_change", "Percentage Change"),
                    ("rsi_overbought", "RSI Overbought"),
                    ("rsi_oversold", "RSI Oversold"),
                    ("macd_crossover", "MACD Crossover"),
                    ("ma_crossover", "Moving Average Crossover"),
                    ("volume_spike", "Volume Spike"),
                    ("bollinger_breach", "Bollinger Band Breach"),
                    ("pattern_completion", "Pattern Completion"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="alert",
            name="condition_value",
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
        migrations.AlterField(
            model_name="alert",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="alert",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="alert",
            name="symbol",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="alert",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alerts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="alertnotification",
            name="channel",
            field=models.CharField(
                choices=[
                    ("websocket", "WebSocket"),
                    ("email", "Email"),
                    ("push", "Push Notification"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="alertnotification",
            name="status",
            field=models.CharField(db_index=True, default="pending", max_length=20),
        ),
        migrations.AlterField(
            model_name="alerttemplate",
            name="alert_type",
            field=models.CharField(
                choices=[
                    ("price_above", "Price Above"),
                    ("price_below", "Price Below"),
                    ("percentage_change", "Percentage Change"),
                    ("rsi_overbought", "RSI Overbought"),
                    ("rsi_oversold", "RSI Oversold"),
                    ("macd_crossover", "MACD Crossover"),
                    ("ma_crossover", "Moving Average Crossover"),
                    ("volume_spike", "Volume Spike"),
                    ("bollinger_breach", "Bollinger Band Breach"),
                    ("pattern_completion", "Pattern Completion"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="dextradingpair",
            name="liquidity_usd",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Total liquidity in USD",
                max_digits=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="dextradingpair",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=18,
                help_text="Current price (quote/base)",
                max_digits=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="dextradingpair",
            name="reserve_base",
            field=models.DecimalField(
                blank=True,
                decimal_places=18,
                help_text="Base asset reserves in the pool",
                max_digits=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="dextradingpair",
            name="reserve_quote",
            field=models.DecimalField(
                blank=True,
                decimal_places=18,
                help_text="Quote asset reserves in the pool",
                max_digits=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="dextradingpair",
            name="volume_24h",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="24h trading volume",
                max_digits=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="dextradingpair",
            name="volume_24h_base",
            field=models.DecimalField(
                blank=True,
                decimal_places=18,
                help_text="24h trading volume in base asset",
                max_digits=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="watchlist",
            name="assets",
            field=models.ManyToManyField(blank=True, to="assets.asset"),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["user", "status"], name="investments_user_id_ce8c7d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["symbol", "status"], name="investments_symbol_0cec96_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["alert_type"], name="investments_alert_t_0808b2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alerthistory",
            index=models.Index(
                fields=["alert", "triggered_at"], name="investments_alert_i_20cccb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alertnotification",
            index=models.Index(
                fields=["alert_history", "status"],
                name="investments_alert_h_504d92_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="alertnotification",
            index=models.Index(
                fields=["status", "created_at"], name="investments_status_01ebe2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alertnotification",
            index=models.Index(
                fields=["channel", "status"], name="investments_channel_6d4f2b_idx"
            ),
        ),
        migrations.AlterModelTable(
            name="alert",
            table="investments_alert",
        ),
        migrations.AddField(
            model_name="optionsgreekshistory",
            name="contract",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="greeks_history",
                to="investments.optioncontract",
            ),
        ),
        migrations.AddField(
            model_name="optionscontractsnapshot",
            name="contract",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="snapshots",
                to="investments.optioncontract",
            ),
        ),
        migrations.AddField(
            model_name="optioncontract",
            name="underlying_asset",
            field=models.ForeignKey(
                help_text="Underlying asset for this option",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="option_contracts",
                to="assets.asset",
            ),
        ),
        migrations.AddField(
            model_name="apikeyusagelog",
            name="api_key",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="usage_logs",
                to="investments.apikey",
            ),
        ),
        migrations.AddField(
            model_name="apikey",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="api_keys",
                to="investments.dataprovider",
            ),
        ),
        migrations.AddIndex(
            model_name="optionsgreekshistory",
            index=models.Index(
                fields=["contract", "timestamp"], name="options_gre_contrac_a8d36b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="optionsgreekshistory",
            index=models.Index(
                fields=["timestamp", "delta"], name="options_gre_timesta_d5f554_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="optionscontractsnapshot",
            index=models.Index(
                fields=["contract", "trade_date"], name="options_con_contrac_5e3cee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="optionscontractsnapshot",
            index=models.Index(
                fields=["trade_date", "implied_volatility"],
                name="options_con_trade_d_d10f01_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="optioncontract",
            index=models.Index(
                fields=["underlying_symbol", "expiry_date"],
                name="option_cont_underly_b093a9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="optioncontract",
            index=models.Index(
                fields=["underlying_symbol", "option_type", "strike_price"],
                name="option_cont_underly_4817e0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="optioncontract",
            index=models.Index(
                fields=["underlying_symbol", "expiry_date", "option_type"],
                name="option_cont_underly_3e5abc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="optioncontract",
            index=models.Index(
                fields=["implied_volatility"], name="option_cont_implied_d0aec9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="optioncontract",
            index=models.Index(fields=["delta"], name="option_cont_delta_a6f7ac_idx"),
        ),
        migrations.AddIndex(
            model_name="optioncontract",
            index=models.Index(fields=["theta"], name="option_cont_theta_7c430d_idx"),
        ),
        migrations.AddIndex(
            model_name="optioncontract",
            index=models.Index(fields=["volume"], name="option_cont_volume_fd8e08_idx"),
        ),
        migrations.AddIndex(
            model_name="optioncontract",
            index=models.Index(
                fields=["open_interest"], name="option_cont_open_in_314589_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="optioncontract",
            index=models.Index(
                fields=["is_active", "is_standard"],
                name="option_cont_is_acti_6e53e0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="apikeyusagelog",
            index=models.Index(
                fields=["api_key", "-created_at"], name="api_key_usa_api_key_a5eccf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="apikeyusagelog",
            index=models.Index(
                fields=["api_key", "success"], name="api_key_usa_api_key_a84bf2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="apikeyusagelog",
            index=models.Index(
                fields=["-created_at"], name="api_key_usa_created_1a2cd6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="apikey",
            index=models.Index(
                fields=["provider", "status", "priority"],
                name="api_keys_provide_04dbfc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="apikey",
            index=models.Index(
                fields=["status", "last_used_at"], name="api_keys_status_84c38b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="apikey",
            index=models.Index(
                fields=["provider", "last_used_at"], name="api_keys_provide_d94d14_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="apikey",
            unique_together={("provider", "name")},
        ),
    ]
