# Generated by Django 4.2.27 on 2026-01-29 19:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0016_add_options_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='EconomicIndicator',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('series_id', models.CharField(db_index=True, help_text="FRED series ID (e.g., 'GDP', 'CPIAUCSL')", max_length=50, unique=True)),
                ('title', models.CharField(help_text='Series title', max_length=500)),
                ('description', models.TextField(blank=True, help_text='Series description')),
                ('units', models.CharField(blank=True, help_text="Units of measurement (e.g., 'Billions of Dollars', 'Percent')", max_length=100)),
                ('frequency', models.CharField(blank=True, choices=[('d', 'Daily'), ('w', 'Weekly'), ('bw', 'Biweekly'), ('m', 'Monthly'), ('q', 'Quarterly'), ('sa', 'Semiannual'), ('a', 'Annual')], help_text='Data frequency (d, w, m, q, a, etc.)', max_length=10)),
                ('seasonal_adjustment', models.CharField(blank=True, help_text="Seasonal adjustment (e.g., 'Seasonally Adjusted Annual Rate')", max_length=100)),
                ('last_updated', models.DateTimeField(blank=True, help_text='When the series was last updated by FRED', null=True)),
                ('observation_start', models.DateField(blank=True, help_text='Earliest available observation date', null=True)),
                ('observation_end', models.DateField(blank=True, help_text='Latest available observation date', null=True)),
                ('popularity_score', models.IntegerField(default=0, help_text='Popularity score based on usage', validators=[django.core.validators.MinValueValidator(0)])),
                ('tags', models.JSONField(blank=True, default=list, help_text="Tags for categorization (e.g., ['gdp', 'inflation', 'employment'])")),
            ],
            options={
                'verbose_name': 'Economic Indicator',
                'verbose_name_plural': 'Economic Indicators',
                'db_table': 'economic_indicators',
                'ordering': ['popularity_score', 'series_id'],
                'indexes': [models.Index(fields=['series_id'], name='economic_in_series__41e85f_idx'), models.Index(fields=['frequency'], name='economic_in_frequen_32574e_idx'), models.Index(fields=['popularity_score'], name='economic_in_popular_10da02_idx'), models.Index(fields=['observation_end'], name='economic_in_observa_10fb9a_idx')],
            },
        ),
        migrations.CreateModel(
            name='EconomicDataCache',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cache_key', models.CharField(db_index=True, help_text="Unique cache key (e.g., 'latest_macro_data', 'gdp_2023')", max_length=200, unique=True)),
                ('data', models.JSONField(help_text='Cached economic data')),
                ('expires_at', models.DateTimeField(db_index=True, help_text='When this cache expires')),
                ('last_fetched', models.DateTimeField(auto_now=True, help_text='When this cache was last fetched')),
            ],
            options={
                'verbose_name': 'Economic Data Cache',
                'verbose_name_plural': 'Economic Data Caches',
                'db_table': 'economic_data_cache',
                'ordering': ['-last_fetched'],
                'indexes': [models.Index(fields=['cache_key'], name='economic_da_cache_k_1d69df_idx'), models.Index(fields=['expires_at'], name='economic_da_expires_0a845c_idx')],
            },
        ),
        migrations.CreateModel(
            name='EconomicDataPoint',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('value', models.DecimalField(decimal_places=6, help_text='Data value', max_digits=20)),
                ('realtime_start', models.DateField(blank=True, help_text='Real-time period start date', null=True)),
                ('realtime_end', models.DateField(blank=True, help_text='Real-time period end date', null=True)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_points', to='investments.economicindicator')),
            ],
            options={
                'verbose_name': 'Economic Data Point',
                'verbose_name_plural': 'Economic Data Points',
                'db_table': 'economic_data_points',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['indicator', 'date'], name='economic_da_indicat_32d961_idx'), models.Index(fields=['date'], name='economic_da_date_3dda6e_idx'), models.Index(fields=['-date'], name='economic_da_date_f2b807_idx')],
                'unique_together': {('indicator', 'date', 'realtime_start')},
            },
        ),
    ]
