# Generated by Django 4.2.27 on 2026-01-29 13:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0006_add_type_specific_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cryptoasset",
            name="fdv",
        ),
        migrations.RemoveField(
            model_name="cryptoasset",
            name="max_supply",
        ),
        migrations.RemoveField(
            model_name="cryptoasset",
            name="tvl",
        ),
        migrations.RemoveField(
            model_name="indexasset",
            name="constituents_count",
        ),
        migrations.RemoveField(
            model_name="indexasset",
            name="weighting_method",
        ),
        migrations.AlterField(
            model_name="cryptoasset",
            name="blockchain",
            field=models.CharField(
                blank=True, help_text="Blockchain network", max_length=100, null=True
            ),
        ),
    ]
