# Generated by Django 4.2.27 on 2026-01-29 13:05

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0005_assetmetricshistoric_assetpriceshistoric_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portfolios', '0002_portfolioperformance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('side', models.CharField(choices=[('long', 'Long'), ('short', 'Short')], default='long', max_length=10)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('1E-8'))])),
                ('avg_entry_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('current_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('unrealized_pnl', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('unrealized_pnl_percent', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10)),
                ('realized_pnl', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('total_fees', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('is_open', models.BooleanField(db_index=True, default=True)),
                ('opened_at', models.DateTimeField()),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='assets.asset')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='portfolios.portfolio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'positions',
                'ordering': ['-opened_at'],
                'indexes': [models.Index(fields=['user', 'is_open'], name='positions_user_id_690d99_idx'), models.Index(fields=['portfolio', 'is_open'], name='positions_portfol_0f0143_idx'), models.Index(fields=['asset', 'is_open'], name='positions_asset_i_3d8024_idx'), models.Index(fields=['-opened_at'], name='positions_opened__6d6241_idx')],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('order_type', models.CharField(choices=[('market', 'Market Order'), ('limit', 'Limit Order'), ('stop', 'Stop Order'), ('stop_limit', 'Stop-Limit Order'), ('oco', 'One-Cancels-Other')], max_length=20)),
                ('side', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=10)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('1E-8'))])),
                ('price', models.DecimalField(blank=True, decimal_places=8, help_text='Limit price for limit orders, null for market orders', max_digits=20, null=True)),
                ('stop_price', models.DecimalField(blank=True, decimal_places=8, help_text='Stop price for stop/stop-limit orders', max_digits=20, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('filled', 'Filled'), ('partially_filled', 'Partially Filled'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('filled_quantity', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20)),
                ('filled_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('average_fill_price', models.DecimalField(blank=True, decimal_places=8, help_text='Average price for partially filled orders', max_digits=20, null=True)),
                ('fees', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('time_in_force', models.CharField(choices=[('day', 'Day'), ('gtc', 'Good Till Cancelled'), ('ioc', 'Immediate or Cancel'), ('fok', 'Fill or Kill')], default='day', max_length=20)),
                ('expiry_date', models.DateTimeField(blank=True, help_text='Order expiration date for GTC orders', null=True)),
                ('notes', models.TextField(blank=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='assets.asset')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('oco_linked_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oco_orders', to='trading.order')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='portfolios.portfolio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'orders',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='orders_user_id_535113_idx'), models.Index(fields=['portfolio', 'status'], name='orders_portfol_31b4c5_idx'), models.Index(fields=['asset', 'status'], name='orders_asset_i_8e5e76_idx'), models.Index(fields=['status', '-created_at'], name='orders_status_f8c8df_idx')],
            },
        ),
    ]
