# Generated by Django 4.2.27 on 2026-01-31 21:17

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0013_country_deleted_at_country_deleted_by_and_more'),
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperTradingAccount',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('cash_balance', models.DecimalField(decimal_places=2, default=Decimal('100000.00'), help_text='Virtual cash balance (default: $100,000)', max_digits=12)),
                ('starting_balance', models.DecimalField(decimal_places=2, default=Decimal('100000.00'), help_text='Starting balance when account was created/reset', max_digits=12)),
                ('total_trades', models.IntegerField(default=0, help_text='Total number of trades executed')),
                ('winning_trades', models.IntegerField(default=0, help_text='Number of profitable trades')),
                ('losing_trades', models.IntegerField(default=0, help_text='Number of unprofitable trades')),
                ('total_return', models.FloatField(default=0.0, help_text='Total return percentage')),
                ('last_reset_at', models.DateTimeField(blank=True, help_text='Last time account was reset', null=True)),
                ('reset_count', models.IntegerField(default=0, help_text='Number of times account has been reset')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paper_trading_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'paper_trading_accounts',
            },
        ),
        migrations.CreateModel(
            name='PaperTrade',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('trade_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=10)),
                ('quantity', models.DecimalField(decimal_places=4, help_text='Quantity traded (can be fractional for crypto)', max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, help_text='Execution price per share/coin', max_digits=12)),
                ('executed_at', models.DateTimeField(auto_now_add=True, help_text='When the trade was executed')),
                ('slippage', models.FloatField(default=0.0, help_text='Simulated slippage percentage (e.g., 0.01 for 1%)')),
                ('total_value', models.DecimalField(decimal_places=2, help_text='Total trade value (quantity * price)', max_digits=14)),
                ('is_winning', models.BooleanField(blank=True, help_text='Whether this trade was profitable (for closed positions)', null=True)),
                ('profit_loss', models.DecimalField(blank=True, decimal_places=2, help_text='Profit/loss for this trade', max_digits=14, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_trades', to='trading.papertradingaccount')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paper_trades', to='assets.asset')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'paper_trades',
            },
        ),
        migrations.AddIndex(
            model_name='papertradingaccount',
            index=models.Index(fields=['user'], name='paper_tradi_user_id_b5376b_idx'),
        ),
        migrations.AddIndex(
            model_name='papertradingaccount',
            index=models.Index(fields=['total_return'], name='paper_tradi_total_r_0b6580_idx'),
        ),
        migrations.AddIndex(
            model_name='papertrade',
            index=models.Index(fields=['account', 'executed_at'], name='paper_trade_account_06f82c_idx'),
        ),
        migrations.AddIndex(
            model_name='papertrade',
            index=models.Index(fields=['asset'], name='paper_trade_asset_i_7faff7_idx'),
        ),
        migrations.AddIndex(
            model_name='papertrade',
            index=models.Index(fields=['trade_type'], name='paper_trade_trade_t_17c239_idx'),
        ),
    ]
