# Generated by Django 4.2.27 on 2026-02-01 02:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("trading", "0002_papertradingaccount_papertrade_and_more"),
        ("assets", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaperPosition",
            fields=[
                ("id", models.UUIDField(primary_key=True, default=uuid.uuid4)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=10)),
                ("avg_price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="paper_positions",
                        to="assets.asset",
                    ),
                ),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to="trading.papertradingaccount",
                    ),
                ),
            ],
            options={
                "db_table": "paper_trading_positions",
                "verbose_name": "Paper Trading Position",
                "verbose_name_plural": "Paper Trading Positions",
            },
        ),
        migrations.CreateModel(
            name="PaperTradingOrder",
            fields=[
                ("id", models.UUIDField(primary_key=True, default=uuid.uuid4)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order_type",
                    models.CharField(
                        choices=[
                            ("market", "Market Order"),
                            ("limit", "Limit Order"),
                            ("stop", "Stop Order"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "side",
                    models.CharField(
                        choices=[("buy", "Buy"), ("sell", "Sell")], max_length=4
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=10)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "stop_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "filled_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("filled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("filled", "Filled"),
                            ("cancelled", "Cancelled"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("rejection_reason", models.TextField(blank=True, default="")),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="paper_orders",
                        to="assets.asset",
                    ),
                ),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="trading.papertradingaccount",
                    ),
                ),
            ],
            options={
                "db_table": "paper_trading_orders",
                "verbose_name": "Paper Trading Order",
                "verbose_name_plural": "Paper Trading Orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="paperposition",
            index=models.Index(
                fields=["portfolio", "asset"], name="trading_pap_portfolio_Asset_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paperposition",
            index=models.Index(fields=["asset"], name="trading_pap_asset_idx"),
        ),
        migrations.AddIndex(
            model_name="papertradingorder",
            index=models.Index(
                fields=["portfolio", "-created_at"],
                name="trading_pap_portfolio_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="papertradingorder",
            index=models.Index(
                fields=["status", "-created_at"], name="trading_pap_status_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="papertradingorder",
            index=models.Index(
                fields=["asset", "-created_at"], name="trading_pap_asset_created_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="paperposition",
            unique_together={("portfolio", "asset")},
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="PaperPosition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        primary_key=True,
                        default=uuid.uuid4,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=10)),
                ("avg_price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="paper_positions",
                        to="assets.asset",
                    ),
                ),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to="trading.papertradingaccount",
                    ),
                ),
            ],
            options={
                "db_table": "paper_trading_positions",
                "verbose_name": "Paper Trading Position",
                "verbose_name_plural": "Paper Trading Positions",
            },
        ),
        migrations.CreateModel(
            name="PaperTradingOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        primary_key=True,
                        default=uuid.uuid4,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order_type",
                    models.CharField(
                        choices=[
                            ("market", "Market Order"),
                            ("limit", "Limit Order"),
                            ("stop", "Stop Order"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "side",
                    models.CharField(
                        choices=[("buy", "Buy"), ("sell", "Sell")], max_length=4
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=10)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "stop_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "filled_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("filled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("filled", "Filled"),
                            ("cancelled", "Cancelled"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("rejection_reason", models.TextField(blank=True, default="")),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="paper_orders",
                        to="assets.asset",
                    ),
                ),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="trading.papertradingaccount",
                    ),
                ),
            ],
            options={
                "db_table": "paper_trading_orders",
                "verbose_name": "Paper Trading Order",
                "verbose_name_plural": "Paper Trading Orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="paperposition",
            index=models.Index(
                fields=["portfolio", "asset"], name="trading_pap_portfolio_Asset_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paperposition",
            index=models.Index(fields=["asset"], name="trading_pap_asset_idx"),
        ),
        migrations.AddIndex(
            model_name="papertradingorder",
            index=models.Index(
                fields=["portfolio", "-created_at"],
                name="trading_pap_portfolio_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="papertradingorder",
            index=models.Index(
                fields=["status", "-created_at"], name="trading_pap_status_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="papertradingorder",
            index=models.Index(
                fields=["asset", "-created_at"], name="trading_pap_asset_created_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="paperposition",
            unique_together={("portfolio", "asset")},
        ),
    ]
