# Generated by Django 4.2.27 on 2025-12-24 20:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioPerformance',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('total_return_pct', models.DecimalField(decimal_places=4, max_digits=10)),
                ('ytd_return_pct', models.DecimalField(decimal_places=4, max_digits=10)),
                ('mtd_return_pct', models.DecimalField(decimal_places=4, max_digits=10)),
                ('sharpe_ratio', models.DecimalField(decimal_places=4, max_digits=8, null=True)),
                ('max_drawdown_pct', models.DecimalField(decimal_places=4, max_digits=8, null=True)),
                ('volatility', models.DecimalField(decimal_places=4, max_digits=8, null=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance', to='portfolios.portfolio')),
            ],
            options={
                'unique_together': {('portfolio', 'date')},
            },
        ),
    ]
