GICS_SECTORS = [
    {
        "code": "XLE",
        "name": "Energy",
        "description": "Companies involved in oil, gas, and consumable fuels exploration and production.",
        "gics_code": 10,
    },
    {
        "code": "XLB",
        "name": "Materials",
        "description": "Companies involved in chemicals, construction materials, and metals mining.",
        "gics_code": 15,
    },
    {
        "code": "XLI",
        "name": "Industrials",
        "description": "Companies manufacturing capital goods and providing commercial services.",
        "gics_code": 20,
    },
    {
        "code": "XLY",
        "name": "Consumer Discretionary",
        "description": "Companies manufacturing non-essential goods including automobiles, apparel, and leisure.",
        "gics_code": 25,
    },
    {
        "code": "XLP",
        "name": "Consumer Staples",
        "description": "Companies producing essential consumer goods including food, beverage, and household products.",
        "gics_code": 30,
    },
    {
        "code": "XLV",
        "name": "Health Care",
        "description": "Companies involved in healthcare equipment, supplies, biotechnology, and life sciences.",
        "gics_code": 35,
    },
    {
        "code": "XLF",
        "name": "Financials",
        "description": "Companies providing financial services including banks, insurance, and capital markets.",
        "gics_code": 40,
    },
    {
        "code": "XLK",
        "name": "Information Technology",
        "description": "Companies developing software, hardware, and IT services.",
        "gics_code": 45,
    },
    {
        "code": "XLC",
        "name": "Communication Services",
        "description": "Companies providing telecommunication, media, and internet services.",
        "gics_code": 50,
    },
    {
        "code": "XLU",
        "name": "Utilities",
        "description": "Companies providing electricity, gas, water, and renewable energy.",
        "gics_code": 55,
    },
    {
        "code": "XLRE",
        "name": "Real Estate",
        "description": "Companies involved in real estate development, investment, and REIT management.",
        "gics_code": 60,
    },
]

GICS_INDUSTRIES = [
    (
        "Health Care",
        "XLV",
        [
            ("HC", "Health Care Equipment & Supplies", 351010),
            ("HC", "Health Care Providers & Services", 351020),
            ("HC", "Health Care Technology", 351030),
            ("HC", "Biotechnology", 351040),
            ("HC", "Pharmaceuticals", 351050),
            ("HC", "Life Sciences Tools & Services", 351060),
        ],
    ),
    (
        "Financials",
        "XLF",
        [
            ("BC", "Banks", 401010),
            ("BC", "Thrifts & Mortgage Finance", 401020),
            ("BC", "Diversified Financial Services", 401030),
            ("BC", "Consumer Finance", 401040),
            ("BC", "Capital Markets", 401050),
            ("IC", "Insurance", 402010),
            ("IC", "Insurance Brokers", 402020),
            ("IC", "Reinsurance", 402030),
        ],
    ),
    (
        "Consumer Discretionary",
        "XLY",
        [
            ("AU", "Automobiles", 251010),
            ("AU", "Automotive Components", 251020),
            ("AU", "Tires & Rubber", 251030),
            ("HD", "Household Durables", 252010),
            ("HD", "Consumer Electronics", 252020),
            ("HD", "Homebuilding", 252030),
            ("HD", "Building Products", 252040),
            ("HD", "Construction Materials", 252050),
            ("DI", "Distributors", 253010),
            ("DI", "Broadline Retail", 253020),
            ("DI", "Specialty Retail", 253030),
            ("TA", "Textiles, Apparel & Luxury Goods", 254010),
            ("RL", "Hotels, Restaurants & Leisure", 255010),
            ("RL", "Diversified Consumer Services", 255020),
        ],
    ),
    (
        "Consumer Staples",
        "XLP",
        [
            ("BE", "Beverages", 301010),
            ("FP", "Food Products", 301020),
            ("TO", "Tobacco", 301030),
            ("HP", "Household Products", 303010),
            ("PC", "Personal Care Products", 303020),
            ("HS", "Hypermarkets & Super Centers", 301040),
            ("DR", "Drug Retail", 301050),
            ("FD", "Food Distributors", 302010),
            ("FR", "Food Retail", 302020),
        ],
    ),
    (
        "Energy",
        "XLE",
        [
            ("OG", "Oil, Gas & Consumable Fuels", 101010),
            ("OE", "Energy Equipment & Services", 101020),
        ],
    ),
    (
        "Industrials",
        "XLI",
        [
            ("AD", "Aerospace & Defense", 201010),
            ("BP", "Building Products", 202010),
            ("CE", "Construction & Engineering", 202020),
            ("EE", "Electrical Equipment", 202030),
            ("IC", "Industrial Conglomerates", 202040),
            ("MA", "Machinery", 203010),
            ("TD", "Trading Companies & Distributors", 203020),
            ("CS", "Commercial Services & Supplies", 204010),
            ("PS", "Professional Services", 204020),
            ("TI", "Transportation Infrastructure", 205010),
            ("AL", "Airlines", 203040),
            ("MT", "Marine Transportation", 203050),
            ("TK", "Trucking", 203060),
            ("RR", "Railroads", 203070),
        ],
    ),
    (
        "Utilities",
        "XLU",
        [
            ("EU", "Electric Utilities", 551010),
            ("GU", "Gas Utilities", 551020),
            ("MU", "Multi-Utilities", 551030),
            ("WU", "Water Utilities", 551040),
            ("IP", "Independent Power Producers & Energy Traders", 551050),
            ("RE", "Renewable Electricity", 551060),
        ],
    ),
    (
        "Information Technology",
        "XLK",
        [
            ("IT", "IT Services", 451020),
            ("SW", "Software", 451030),
            ("HW", "Hardware", 452010),
            ("SC", "Semiconductors", 452020),
            ("EC", "Electronic Equipment & Components", 452030),
            ("TS", "Technology Hardware, Storage & Peripherals", 452040),
            ("OE", "Office Electronics", 452050),
            ("CE", "Communications Equipment", 452060),
            ("TD", "Technology Distributors", 453010),
            ("EC", "Electronic Components", 453020),
        ],
    ),
    (
        "Real Estate",
        "XLRE",
        [
            ("RE", "Equity Real Estate Investment Trusts (REITs)", 601010),
            ("RD", "Real Estate Development & Operations", 602010),
            ("RO", "Real Estate Operating Companies", 602020),
            ("MR", "Mortgage Real Estate Investment Trusts", 601020),
        ],
    ),
    (
        "Communication Services",
        "XLC",
        [
            ("DT", "Diversified Telecommunication Services", 501010),
            ("WT", "Wireless Telecommunication Services", 501020),
            ("IT", "Integrated Telecommunication Services", 501030),
            ("ME", "Media", 502010),
            ("EN", "Entertainment", 502020),
            ("IM", "Interactive Media & Services", 502030),
            ("PU", "Publishing", 502040),
            ("BR", "Broadcasting", 502050),
        ],
    ),
    (
        "Materials",
        "XLB",
        [
            ("CH", "Chemicals", 151010),
            ("CM", "Construction Materials", 151020),
            ("CP", "Containers & Packaging", 151030),
            ("MM", "Metals & Mining", 151040),
            ("PF", "Paper & Forest Products", 151050),
        ],
    ),
]

COMMON_TIMEZONES = [
    {
        "name": "America/New_York",
        "utc_offset": -5,
        "abbreviation": "EST",
        "is_dst_observed": True,
    },
    {
        "name": "America/Chicago",
        "utc_offset": -6,
        "abbreviation": "CST",
        "is_dst_observed": True,
    },
    {
        "name": "America/Denver",
        "utc_offset": -7,
        "abbreviation": "MST",
        "is_dst_observed": True,
    },
    {
        "name": "America/Los_Angeles",
        "utc_offset": -8,
        "abbreviation": "PST",
        "is_dst_observed": True,
    },
    {
        "name": "America/Anchorage",
        "utc_offset": -9,
        "abbreviation": "AKST",
        "is_dst_observed": True,
    },
    {
        "name": "Pacific/Honolulu",
        "utc_offset": -10,
        "abbreviation": "HST",
        "is_dst_observed": False,
    },
    {
        "name": "Europe/London",
        "utc_offset": 0,
        "abbreviation": "GMT",
        "is_dst_observed": True,
    },
    {
        "name": "Europe/Paris",
        "utc_offset": 1,
        "abbreviation": "CET",
        "is_dst_observed": True,
    },
    {
        "name": "Europe/Berlin",
        "utc_offset": 1,
        "abbreviation": "CET",
        "is_dst_observed": True,
    },
    {
        "name": "Europe/Zurich",
        "utc_offset": 1,
        "abbreviation": "CET",
        "is_dst_observed": True,
    },
    {
        "name": "Europe/Amsterdam",
        "utc_offset": 1,
        "abbreviation": "CET",
        "is_dst_observed": True,
    },
    {
        "name": "Europe/Brussels",
        "utc_offset": 1,
        "abbreviation": "CET",
        "is_dst_observed": True,
    },
    {
        "name": "Europe/Vienna",
        "utc_offset": 1,
        "abbreviation": "CET",
        "is_dst_observed": True,
    },
    {
        "name": "Europe/Madrid",
        "utc_offset": 1,
        "abbreviation": "CET",
        "is_dst_observed": True,
    },
    {
        "name": "Europe/Rome",
        "utc_offset": 1,
        "abbreviation": "CET",
        "is_dst_observed": True,
    },
    {
        "name": "Europe/Stockholm",
        "utc_offset": 1,
        "abbreviation": "CET",
        "is_dst_observed": True,
    },
    {
        "name": "Europe/Oslo",
        "utc_offset": 1,
        "abbreviation": "CET",
        "is_dst_observed": True,
    },
    {
        "name": "Europe/Copenhagen",
        "utc_offset": 1,
        "abbreviation": "CET",
        "is_dst_observed": True,
    },
    {
        "name": "Europe/Helsinki",
        "utc_offset": 2,
        "abbreviation": "EET",
        "is_dst_observed": True,
    },
    {
        "name": "Europe/Warsaw",
        "utc_offset": 1,
        "abbreviation": "CET",
        "is_dst_observed": True,
    },
    {
        "name": "Europe/Moscow",
        "utc_offset": 3,
        "abbreviation": "MSK",
        "is_dst_observed": False,
    },
    {
        "name": "Asia/Tokyo",
        "utc_offset": 9,
        "abbreviation": "JST",
        "is_dst_observed": False,
    },
    {
        "name": "Asia/Shanghai",
        "utc_offset": 8,
        "abbreviation": "CST",
        "is_dst_observed": False,
    },
    {
        "name": "Asia/Hong_Kong",
        "utc_offset": 8,
        "abbreviation": "HKT",
        "is_dst_observed": False,
    },
    {
        "name": "Asia/Singapore",
        "utc_offset": 8,
        "abbreviation": "SGT",
        "is_dst_observed": False,
    },
    {
        "name": "Asia/Seoul",
        "utc_offset": 9,
        "abbreviation": "KST",
        "is_dst_observed": False,
    },
    {
        "name": "Asia/Kolkata",
        "utc_offset": 5,
        "abbreviation": "IST",
        "is_dst_observed": False,
    },
    {
        "name": "Asia/Bangkok",
        "utc_offset": 7,
        "abbreviation": "ICT",
        "is_dst_observed": False,
    },
    {
        "name": "Asia/Jakarta",
        "utc_offset": 7,
        "abbreviation": "WIB",
        "is_dst_observed": False,
    },
    {
        "name": "Asia/Taipei",
        "utc_offset": 8,
        "abbreviation": "CST",
        "is_dst_observed": False,
    },
    {
        "name": "Australia/Sydney",
        "utc_offset": 11,
        "abbreviation": "AEST",
        "is_dst_observed": True,
    },
    {
        "name": "Australia/Melbourne",
        "utc_offset": 11,
        "abbreviation": "AEST",
        "is_dst_observed": True,
    },
    {
        "name": "Australia/Perth",
        "utc_offset": 8,
        "abbreviation": "AWST",
        "is_dst_observed": False,
    },
    {
        "name": "Pacific/Auckland",
        "utc_offset": 13,
        "abbreviation": "NZST",
        "is_dst_observed": True,
    },
    {
        "name": "America/Toronto",
        "utc_offset": -5,
        "abbreviation": "EST",
        "is_dst_observed": True,
    },
    {
        "name": "America/Vancouver",
        "utc_offset": -8,
        "abbreviation": "PST",
        "is_dst_observed": True,
    },
    {
        "name": "America/Mexico_City",
        "utc_offset": -6,
        "abbreviation": "CST",
        "is_dst_observed": True,
    },
    {
        "name": "America/Sao_Paulo",
        "utc_offset": -3,
        "abbreviation": "BRT",
        "is_dst_observed": False,
    },
    {
        "name": "America/Buenos_Aires",
        "utc_offset": -3,
        "abbreviation": "ART",
        "is_dst_observed": False,
    },
    {
        "name": "America/Bogota",
        "utc_offset": -5,
        "abbreviation": "COT",
        "is_dst_observed": False,
    },
    {
        "name": "America/Lima",
        "utc_offset": -5,
        "abbreviation": "PET",
        "is_dst_observed": False,
    },
    {
        "name": "Asia/Dubai",
        "utc_offset": 4,
        "abbreviation": "GST",
        "is_dst_observed": False,
    },
    {
        "name": "Asia/Jerusalem",
        "utc_offset": 2,
        "abbreviation": "IST",
        "is_dst_observed": True,
    },
    {
        "name": "Africa/Johannesburg",
        "utc_offset": 2,
        "abbreviation": "SAST",
        "is_dst_observed": False,
    },
    {
        "name": "Africa/Lagos",
        "utc_offset": 1,
        "abbreviation": "WAT",
        "is_dst_observed": False,
    },
    {
        "name": "Africa/Cairo",
        "utc_offset": 2,
        "abbreviation": "EET",
        "is_dst_observed": False,
    },
]
