# Generated by Django 4.2.27 on 2025-12-24 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolios', '0001_initial'),
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='holding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='portfolios.holding'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='portfolios.portfolio'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='investments.transactiontype'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['portfolio', '-date'], name='investments_portfol_44313e_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_type'], name='investments_transac_50b994_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['asset'], name='investments_asset_i_6643fd_idx'),
        ),
    ]
