# Generated by Django 4.2.27 on 2025-12-24 20:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_pricehistory'),
        ('investments', '0003_currency_exchangerate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dividend',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ex_date', models.DateField()),
                ('pay_date', models.DateField()),
                ('amount_per_share', models.DecimalField(decimal_places=6, max_digits=15)),
                ('declared_date', models.DateField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dividends', to='assets.asset')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='investments.currency')),
            ],
            options={
                'ordering': ['-ex_date'],
            },
        ),
        migrations.CreateModel(
            name='CorporateAction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('ratio', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('description', models.TextField()),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.asset')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
