# Generated by Django 4.2.27 on 2025-12-27 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0008_dataprovider_delete_dataproviderconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataprovider',
            name='priority',
            field=models.PositiveSmallIntegerField(default=10, help_text='Lower is higher priority'),
        ),
    ]
