# Generated by Django 4.2.27 on 2026-01-30 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0011_country_alpha_3_country_numeric_code_and_more'),
        ('investments', '0017_economicindicator_economicdatacache_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currencies', to='assets.country'),
        ),
        migrations.AddField(
            model_name='currency',
            name='numeric_code',
            field=models.CharField(blank=True, max_length=3, null=True, unique=True),
        ),
    ]
