# Generated by Django 4.2.27 on 2026-01-31 21:22

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0013_country_deleted_at_country_deleted_by_and_more'),
        ('portfolios', '0002_portfolioperformance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investments', '0050_dashboard_layout'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('trigger_value', models.DecimalField(decimal_places=4, max_digits=20)),
                ('asset_price', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('asset_name', models.CharField(blank=True, max_length=200)),
                ('email_sent', models.BooleanField(default=False)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('email_error', models.TextField(blank=True)),
                ('push_sent', models.BooleanField(default=False)),
                ('push_sent_at', models.DateTimeField(blank=True, null=True)),
                ('push_error', models.TextField(blank=True)),
                ('sms_sent', models.BooleanField(default=False)),
                ('sms_sent_at', models.DateTimeField(blank=True, null=True)),
                ('sms_error', models.TextField(blank=True)),
                ('in_app_sent', models.BooleanField(default=False)),
                ('in_app_sent_at', models.DateTimeField(blank=True, null=True)),
                ('viewed', models.BooleanField(default=False)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('dismissed', models.BooleanField(default=False)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('priority', models.CharField(default='normal', max_length=20)),
                ('read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('action_url', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('push', 'Push Notification'), ('sms', 'SMS'), ('in_app', 'In-App')], max_length=20)),
                ('alert_type', models.CharField(choices=[('price_above', 'Price Above'), ('price_below', 'Price Below'), ('percent_change', 'Percent Change'), ('volume_above', 'Volume Above'), ('news_mention', 'News Mention'), ('portfolio_change', 'Portfolio Value Change'), ('volatility', 'Volatility Alert'), ('rsi', 'RSI Level'), ('earning_above', 'Earnings Above Estimate'), ('earning_below', 'Earnings Below Estimate'), ('dividend', 'Dividend Announced'), ('custom', 'Custom Condition')], max_length=30)),
                ('enabled', models.BooleanField(default=True)),
                ('quiet_hours_enabled', models.BooleanField(default=False)),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceAttribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('attribution_type', models.CharField(choices=[('SECURITY', 'By Security'), ('SECTOR', 'By Sector'), ('FACTOR', 'By Factor'), ('ASSET_CLASS', 'By Asset Class')], max_length=20)),
                ('category', models.CharField(help_text='Security, sector, or factor name', max_length=100)),
                ('category_return', models.DecimalField(decimal_places=4, max_digits=10)),
                ('benchmark_return', models.DecimalField(decimal_places=4, max_digits=10)),
                ('allocation_effect', models.DecimalField(decimal_places=4, max_digits=10)),
                ('selection_effect', models.DecimalField(decimal_places=4, max_digits=10)),
                ('interaction_effect', models.DecimalField(decimal_places=4, max_digits=10)),
                ('total_attribution', models.DecimalField(decimal_places=4, max_digits=10)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-period_end', '-calculated_at'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioAssetClassAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_class', models.CharField(choices=[('stock', 'Stock'), ('bond', 'Bond'), ('crypto', 'Crypto'), ('cash', 'Cash'), ('commodity', 'Commodity'), ('etf', 'ETF'), ('real_estate', 'Real Estate'), ('other', 'Other')], max_length=50)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['asset_class'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioBeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beta', models.DecimalField(decimal_places=4, max_digits=10)),
                ('correlation', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('r_squared', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('calculation_period_days', models.IntegerField(default=252)),
            ],
            options={
                'ordering': ['-calculated_at'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioConcentrationRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('concentration_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('concentration_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('VERY_HIGH', 'Very High')], max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-percentage'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioDrift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_class', models.CharField(max_length=50)),
                ('current_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('target_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('drift_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('drift_level', models.CharField(choices=[('WITHIN_TOLERANCE', 'Within Tolerance'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], max_length=20)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-calculated_at'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioGeographicAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('region', models.CharField(blank=True, default='', max_length=100)),
                ('country_code', models.CharField(blank=True, default='', max_length=3)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-percentage'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioRiskMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('calculation_period_days', models.IntegerField(default=252)),
                ('volatility_30d', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('volatility_90d', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('volatility_1y', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('sharpe_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('sortino_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('max_drawdown', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('var_95', models.DecimalField(blank=True, decimal_places=4, help_text='Value at Risk 95%', max_digits=12, null=True)),
                ('var_99', models.DecimalField(blank=True, decimal_places=4, help_text='Value at Risk 99%', max_digits=12, null=True)),
                ('risk_score', models.IntegerField(blank=True, null=True)),
                ('risk_level', models.CharField(blank=True, choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('VERY_HIGH', 'Very High')], max_length=20, null=True)),
            ],
            options={
                'ordering': ['-calculated_at'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioSectorAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(max_length=100)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-percentage'],
            },
        ),
        migrations.CreateModel(
            name='RebalancingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_REVIEW', 'Pending Review'), ('APPROVED', 'Approved'), ('EXECUTING', 'Executing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('total_trades', models.IntegerField(default=0)),
                ('estimated_total_value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('actual_total_value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('tax_impact', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RebalancingSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_class', models.CharField(max_length=50)),
                ('action', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=10)),
                ('current_quantity', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('current_value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('suggested_quantity', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('suggested_value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('current_allocation', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('target_allocation', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('priority', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=20)),
                ('tax_implication', models.CharField(choices=[('GAIN', 'Capital Gain'), ('LOSS', 'Capital Loss'), ('NEUTRAL', 'Neutral')], default='NEUTRAL', max_length=20)),
                ('estimated_trade_value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('reason', models.TextField(blank=True, help_text='Explanation for this rebalancing suggestion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('EXECUTED', 'Executed'), ('CANCELLED', 'Cancelled'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=20)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScreenerPreset',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('filters', models.JSONField(default=dict)),
                ('is_public', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='TargetAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_class', models.CharField(choices=[('stock', 'Stock'), ('bond', 'Bond'), ('crypto', 'Crypto'), ('cash', 'Cash'), ('commodity', 'Commodity'), ('etf', 'ETF'), ('real_estate', 'Real Estate'), ('other', 'Other')], max_length=50)),
                ('target_percentage', models.DecimalField(decimal_places=2, help_text='Target allocation percentage (0-100)', max_digits=5)),
                ('tolerance_percentage', models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Tolerance band (+/- percentage)', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['asset_class'],
            },
        ),
        migrations.CreateModel(
            name='TaxLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=20)),
                ('cost_basis', models.DecimalField(decimal_places=2, max_digits=20)),
                ('current_value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('purchase_date', models.DateField()),
                ('current_price', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('unrealized_gain_loss', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('gain_loss_percentage', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('holding_period_days', models.IntegerField(default=0)),
                ('is_long_term', models.BooleanField(default=False)),
                ('wash_sale_risk', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['purchase_date'],
            },
        ),
        migrations.RemoveField(
            model_name='alerthistory',
            name='alert',
        ),
        migrations.RemoveField(
            model_name='alertnotification',
            name='alert_history',
        ),
        migrations.RemoveField(
            model_name='alerttemplate',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='alert',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='alert',
            name='investments_status_101e9c_idx',
        ),
        migrations.RemoveIndex(
            model_name='alert',
            name='investments_user_id_60abc2_idx',
        ),
        migrations.RemoveIndex(
            model_name='alert',
            name='investments_trigger_e5bdb9_idx',
        ),
        migrations.RemoveIndex(
            model_name='alert',
            name='investments_last_tr_f6394d_idx',
        ),
        migrations.RemoveIndex(
            model_name='alert',
            name='investments_symbol_0cec96_idx',
        ),
        migrations.RemoveIndex(
            model_name='alert',
            name='investments_alert_t_0808b2_idx',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='cooldown_seconds',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='delivery_channels',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='description',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='last_notified_at',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='symbol',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='triggered_count',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='valid_from',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='valid_until',
        ),
        migrations.AddField(
            model_name='alert',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='alert',
            name='condition_secondary_value',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='custom_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='frequency',
            field=models.CharField(choices=[('once', 'One Time'), ('always', 'Every Time'), ('hourly', 'Hourly Max'), ('daily', 'Daily Max'), ('weekly', 'Weekly Max')], default='once', max_length=20),
        ),
        migrations.AddField(
            model_name='alert',
            name='portfolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='portfolios.portfolio'),
        ),
        migrations.AddField(
            model_name='alert',
            name='send_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alert',
            name='send_in_app',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='send_push',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='send_sms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alert',
            name='trigger_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='benchmark',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='benchmark',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='currency',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='impact_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='News impact score on assets (0-100)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='mentioned_assets',
            field=models.ManyToManyField(blank=True, help_text='Assets explicitly mentioned in the article', related_name='news_mentions', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='summary',
            field=models.TextField(blank=True, help_text='AI-generated summary of the article', null=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='summary_generated_at',
            field=models.DateTimeField(blank=True, help_text='When the summary was generated', null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('price_above', 'Price Above'), ('price_below', 'Price Below'), ('percent_change', 'Percent Change'), ('volume_above', 'Volume Above'), ('news_mention', 'News Mention'), ('portfolio_change', 'Portfolio Value Change'), ('volatility', 'Volatility Alert'), ('rsi', 'RSI Level'), ('earning_above', 'Earnings Above Estimate'), ('earning_below', 'Earnings Below Estimate'), ('dividend', 'Dividend Announced'), ('custom', 'Custom Condition')], max_length=30),
        ),
        migrations.AlterField(
            model_name='alert',
            name='condition_operator',
            field=models.CharField(default='>=', max_length=5),
        ),
        migrations.AlterField(
            model_name='alert',
            name='condition_value',
            field=models.DecimalField(decimal_places=4, max_digits=20),
        ),
        migrations.AlterField(
            model_name='alert',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='corporateaction',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corporate_actions', to='assets.asset'),
        ),
        migrations.AlterField(
            model_name='dashboardlayout',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_layouts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='assets.asset'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='investments.transactiontype'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['alert_type', 'status'], name='investments_alert_t_65c62c_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['asset', 'status'], name='investments_asset_i_e0d45b_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['user', 'alert_type'], name='investments_user_id_fff3be_idx'),
        ),
        migrations.AlterModelTable(
            name='alert',
            table=None,
        ),
        migrations.DeleteModel(
            name='AlertHistory',
        ),
        migrations.DeleteModel(
            name='AlertNotification',
        ),
        migrations.DeleteModel(
            name='AlertTemplate',
        ),
        migrations.AddField(
            model_name='taxlot',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_lots', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='taxlot',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_lots', to='portfolios.portfolio'),
        ),
        migrations.AddField(
            model_name='targetallocation',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_allocations', to='portfolios.portfolio'),
        ),
        migrations.AddField(
            model_name='screenerpreset',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='screenerpreset',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screener_presets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rebalancingsuggestion',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rebalancing_suggestions', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='rebalancingsuggestion',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rebalancing_suggestions', to='portfolios.portfolio'),
        ),
        migrations.AddField(
            model_name='rebalancingsession',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rebalancing_sessions', to='portfolios.portfolio'),
        ),
        migrations.AddField(
            model_name='portfoliosectorallocation',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sector_allocations', to='portfolios.portfolio'),
        ),
        migrations.AddField(
            model_name='portfolioriskmetrics',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_metrics', to='portfolios.portfolio'),
        ),
        migrations.AddField(
            model_name='portfoliogeographicallocation',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geographic_allocations', to='portfolios.portfolio'),
        ),
        migrations.AddField(
            model_name='portfoliodrift',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drift_records', to='portfolios.portfolio'),
        ),
        migrations.AddField(
            model_name='portfolioconcentrationrisk',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concentration_records', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='portfolioconcentrationrisk',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concentration_risks', to='portfolios.portfolio'),
        ),
        migrations.AddField(
            model_name='portfoliobeta',
            name='benchmark',
            field=models.ForeignKey(help_text='Benchmark asset (e.g., SPY)', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='portfoliobeta',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beta_records', to='portfolios.portfolio'),
        ),
        migrations.AddField(
            model_name='portfolioassetclassallocation',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_class_allocations', to='portfolios.portfolio'),
        ),
        migrations.AddField(
            model_name='performanceattribution',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_attributions', to='portfolios.portfolio'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_alert_trigger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='investments.alerttrigger'),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alerttrigger',
            name='alert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='investments.alert'),
        ),
        migrations.AlterUniqueTogether(
            name='targetallocation',
            unique_together={('portfolio', 'asset_class')},
        ),
        migrations.AlterUniqueTogether(
            name='screenerpreset',
            unique_together={('user', 'name')},
        ),
        migrations.AddIndex(
            model_name='portfoliosectorallocation',
            index=models.Index(fields=['portfolio', 'sector'], name='investments_portfol_a34dee_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='portfoliosectorallocation',
            unique_together={('portfolio', 'sector')},
        ),
        migrations.AddIndex(
            model_name='portfolioriskmetrics',
            index=models.Index(fields=['portfolio', 'calculated_at'], name='investments_portfol_645e61_idx'),
        ),
        migrations.AddIndex(
            model_name='portfoliogeographicallocation',
            index=models.Index(fields=['portfolio', 'country'], name='investments_portfol_4f4144_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='portfoliogeographicallocation',
            unique_together={('portfolio', 'country')},
        ),
        migrations.AddIndex(
            model_name='portfolioconcentrationrisk',
            index=models.Index(fields=['portfolio', 'asset'], name='investments_portfol_2f22ee_idx'),
        ),
        migrations.AddIndex(
            model_name='portfoliobeta',
            index=models.Index(fields=['portfolio', 'benchmark'], name='investments_portfol_22fd22_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolioassetclassallocation',
            index=models.Index(fields=['portfolio', 'asset_class'], name='investments_portfol_9ca21b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='portfolioassetclassallocation',
            unique_together={('portfolio', 'asset_class')},
        ),
        migrations.AddIndex(
            model_name='performanceattribution',
            index=models.Index(fields=['portfolio', 'period_start', 'period_end'], name='investments_portfol_98ad74_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='notificationpreference',
            unique_together={('user', 'channel', 'alert_type')},
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'read', 'created_at'], name='investments_user_id_eec586_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type', 'created_at'], name='investments_notific_651f92_idx'),
        ),
        migrations.AddIndex(
            model_name='alerttrigger',
            index=models.Index(fields=['alert', 'triggered_at'], name='investments_alert_i_85d097_idx'),
        ),
        migrations.AddIndex(
            model_name='alerttrigger',
            index=models.Index(fields=['viewed', 'dismissed'], name='investments_viewed_7f9aa3_idx'),
        ),
    ]
