# Generated by Django 4.2.27 on 2026-01-29 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0007_remove_cryptoasset_circulating_supply_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalIndicatorValue',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('indicator_type', models.CharField(choices=[('sma', 'Simple Moving Average'), ('ema', 'Exponential Moving Average'), ('wma', 'Weighted Moving Average'), ('bollinger_upper', 'Bollinger Upper'), ('bollinger_middle', 'Bollinger Middle'), ('bollinger_lower', 'Bollinger Lower'), ('rsi', 'RSI'), ('macd', 'MACD'), ('macd_signal', 'MACD Signal'), ('stochastic_k', 'Stochastic %K'), ('stochastic_d', 'Stochastic %D'), ('cci', 'CCI'), ('williams_r', 'Williams %R'), ('atr', 'ATR'), ('obv', 'OBV'), ('mfi', 'MFI'), ('ad', 'A/D Line')], max_length=50)),
                ('timeframe', models.CharField(choices=[('1m', '1 Minute'), ('5m', '5 Minutes'), ('15m', '15 Minutes'), ('1h', '1 Hour'), ('4h', '4 Hours'), ('1d', '1 Day'), ('1w', '1 Week')], default='1d', max_length=10)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('value', models.DecimalField(decimal_places=6, max_digits=15)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('signal', models.CharField(blank=True, choices=[('buy', 'Buy'), ('sell', 'Sell'), ('neutral', 'Neutral')], max_length=20, null=True)),
                ('strength', models.IntegerField(blank=True, choices=[(1, 'Weak'), (2, 'Moderate'), (3, 'Strong')], null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicator_values', to='assets.asset')),
            ],
            options={
                'db_table': 'technical_indicator_values',
                'indexes': [models.Index(fields=['asset', 'indicator_type', 'timeframe'], name='technical_i_asset_i_b6576c_idx'), models.Index(fields=['asset', 'timestamp'], name='technical_i_asset_i_410705_idx'), models.Index(fields=['indicator_type', 'signal'], name='technical_i_indicat_9d0820_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChartDrawingManager',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('layout', models.JSONField(default=dict)),
                ('indicators', models.JSONField(default=list)),
                ('default_timeframe', models.CharField(choices=[('1m', '1 Minute'), ('5m', '5 Minutes'), ('15m', '15 Minutes'), ('1h', '1 Hour'), ('4h', '4 Hours'), ('1d', '1 Day'), ('1w', '1 Week')], default='1d', max_length=10)),
                ('chart_type', models.CharField(choices=[('line', 'Line Chart'), ('candlestick', 'Candlestick'), ('area', 'Area Chart'), ('bar', 'Bar Chart')], default='line', max_length=20)),
                ('show_volume', models.BooleanField(default=True)),
                ('show_indicators', models.BooleanField(default=True)),
                ('show_drawings', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chart_managers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chart_layouts',
                'indexes': [models.Index(fields=['user', 'is_default'], name='chart_layou_user_id_f2c3a1_idx')],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ChartDrawing',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('drawing_type', models.CharField(choices=[('horizontal_line', 'Horizontal Line'), ('vertical_line', 'Vertical Line'), ('trend_line', 'Trend Line'), ('support_resistance', 'Support/Resistance'), ('fibonacci', 'Fibonacci Retracement'), ('rectangle', 'Rectangle'), ('text', 'Text Annotation')], max_length=50)),
                ('timeframe', models.CharField(choices=[('1m', '1 Minute'), ('5m', '5 Minutes'), ('15m', '15 Minutes'), ('1h', '1 Hour'), ('4h', '4 Hours'), ('1d', '1 Day'), ('1w', '1 Week')], default='1d', max_length=10)),
                ('start_x', models.DecimalField(decimal_places=2, max_digits=5)),
                ('start_y', models.DecimalField(decimal_places=2, max_digits=5)),
                ('end_x', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('end_y', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('color', models.CharField(default='#ef4444', max_length=20)),
                ('width', models.IntegerField(default=2)),
                ('line_style', models.CharField(choices=[('solid', 'Solid'), ('dashed', 'Dashed')], default='solid', max_length=20)),
                ('text', models.TextField(blank=True, null=True)),
                ('fibonacci_levels', models.JSONField(blank=True, default=list)),
                ('visible', models.BooleanField(default=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drawings', to='assets.asset')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chart_drawings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chart_drawings',
                'indexes': [models.Index(fields=['user', 'asset', 'timeframe'], name='chart_drawi_user_id_6ef863_idx'), models.Index(fields=['drawing_type'], name='chart_drawi_drawing_57b920_idx'), models.Index(fields=['visible'], name='chart_drawi_visible_0b9f21_idx')],
            },
        ),
    ]
