# Generated by Django 4.2.27 on 2025-12-24 20:15

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0002_pricehistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False)),
                ('is_paper_trading', models.BooleanField(default=False, help_text='Simulated portfolio')),
                ('base_currency', models.CharField(default='USD', max_length=3)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('1E-8'))])),
                ('average_buy_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='holdings', to='assets.asset')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='portfolios.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioSnapshot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('cash_balance', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('invested_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('total_return', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('daily_return', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='portfolios.portfolio')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['portfolio', '-date'], name='portfolios__portfol_b91428_idx')],
                'unique_together': {('portfolio', 'date')},
            },
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['user'], name='portfolios__user_id_31c861_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['is_public'], name='portfolios__is_publ_d8cf30_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='portfolio',
            unique_together={('user', 'name')},
        ),
        migrations.AddIndex(
            model_name='holding',
            index=models.Index(fields=['portfolio'], name='portfolios__portfol_2d92ef_idx'),
        ),
        migrations.AddIndex(
            model_name='holding',
            index=models.Index(fields=['asset'], name='portfolios__asset_i_bc84be_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='holding',
            unique_together={('portfolio', 'asset')},
        ),
    ]
