# Generated by Django 4.2.27 on 2026-01-31 21:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerConnection',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('broker', models.CharField(choices=[('alpaca', 'Alpaca'), ('binance', 'Binance'), ('coinbase', 'Coinbase'), ('kraken', 'Kraken'), ('ibkr', 'Interactive Brokers')], max_length=20)),
                ('account_type', models.CharField(choices=[('paper', 'Paper Trading'), ('live', 'Live Trading')], max_length=10)),
                ('account_id', models.CharField(blank=True, max_length=100)),
                ('account_name', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('error', 'Error'), ('pending', 'Pending Verification')], default='pending', max_length=20)),
                ('api_key_encrypted', models.BinaryField()),
                ('api_secret_encrypted', models.BinaryField()),
                ('passphrase_encrypted', models.BinaryField(blank=True, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('sync_enabled', models.BooleanField(default=True)),
                ('sync_interval_minutes', models.IntegerField(default=15)),
                ('permissions', models.JSONField(default=dict)),
                ('rate_limit_remaining', models.IntegerField(default=0)),
                ('rate_limit_reset_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broker_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'broker_connections',
            },
        ),
        migrations.CreateModel(
            name='PortfolioSyncLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sync_type', models.CharField(choices=[('full', 'Full Sync'), ('incremental', 'Incremental Sync'), ('positions', 'Positions Only'), ('transactions', 'Transactions Only'), ('orders', 'Orders Only')], max_length=20)),
                ('status', models.CharField(choices=[('started', 'Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='started', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('positions_synced', models.IntegerField(default=0)),
                ('transactions_synced', models.IntegerField(default=0)),
                ('orders_synced', models.IntegerField(default=0)),
                ('errors_count', models.IntegerField(default=0)),
                ('errors', models.JSONField(default=list)),
                ('duration_ms', models.IntegerField(default=0)),
                ('api_calls_made', models.IntegerField(default=0)),
                ('data_volume_bytes', models.IntegerField(default=0)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='brokers.brokerconnection')),
            ],
            options={
                'db_table': 'portfolio_sync_logs',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['connection', 'started_at'], name='portfolio_s_connect_f58c73_idx'), models.Index(fields=['connection', 'status'], name='portfolio_s_connect_6be6a4_idx')],
            },
        ),
        migrations.CreateModel(
            name='BrokerTransaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('transaction_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('transfer', 'Transfer'), ('fee', 'Fee'), ('dividend', 'Dividend'), ('split', 'Stock Split'), ('spin_off', 'Spin Off'), ('merger', 'Merger'), ('other', 'Other')], max_length=20)),
                ('symbol', models.CharField(blank=True, max_length=20)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                ('price', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('fee', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='pending', max_length=20)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('external_transaction_id', models.CharField(blank=True, max_length=200)),
                ('order_id', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(default=dict)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='brokers.brokerconnection')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'broker_transactions',
                'indexes': [models.Index(fields=['connection', 'executed_at'], name='broker_tran_connect_f9f85a_idx'), models.Index(fields=['connection', 'symbol'], name='broker_tran_connect_428651_idx'), models.Index(fields=['connection', 'transaction_type'], name='broker_tran_connect_afa585_idx')],
            },
        ),
        migrations.CreateModel(
            name='BrokerPosition',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('symbol', models.CharField(max_length=20)),
                ('asset_id', models.CharField(blank=True, max_length=100)),
                ('side', models.CharField(choices=[('long', 'Long'), ('short', 'Short'), ('neutral', 'Neutral')], default='long', max_length=10)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=20)),
                ('avg_entry_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('current_price', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                ('market_value', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('unrealized_pl', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('unrealized_pl_percent', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('cost_basis', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('commission', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('last_price_update', models.DateTimeField(blank=True, null=True)),
                ('external_position_id', models.CharField(blank=True, max_length=200)),
                ('metadata', models.JSONField(default=dict)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='brokers.brokerconnection')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'broker_positions',
                'indexes': [models.Index(fields=['connection', 'symbol'], name='broker_posi_connect_cb11b0_idx'), models.Index(fields=['connection', 'side'], name='broker_posi_connect_558d88_idx')],
                'unique_together': {('connection', 'symbol', 'external_position_id')},
            },
        ),
        migrations.CreateModel(
            name='BrokerOrder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('order_type', models.CharField(choices=[('market', 'Market'), ('limit', 'Limit'), ('stop', 'Stop'), ('stop_limit', 'Stop Limit'), ('trailing_stop', 'Trailing Stop')], max_length=20)),
                ('side', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=10)),
                ('symbol', models.CharField(max_length=20)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=20)),
                ('filled_quantity', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('limit_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('stop_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('trailing_amount', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('trailing_percent', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('time_in_force', models.CharField(choices=[('day', 'Day'), ('gtc', 'Good Till Canceled'), ('ioc', 'Immediate Or Cancel'), ('fok', 'Fill Or Kill'), ('opg', 'At The Opening'), ('cls', 'Close')], default='day', max_length=10)),
                ('status', models.CharField(choices=[('pending_new', 'Pending New'), ('accepted', 'Accepted'), ('pending_cancel', 'Pending Cancel'), ('partial_filled', 'Partially Filled'), ('filled', 'Filled'), ('canceled', 'Canceled'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending_new', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('filled_at', models.DateTimeField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('avg_fill_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('commission', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('external_order_id', models.CharField(blank=True, max_length=200)),
                ('parent_order_id', models.CharField(blank=True, max_length=200)),
                ('legs', models.JSONField(default=list)),
                ('metadata', models.JSONField(default=dict)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='brokers.brokerconnection')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'broker_orders',
                'indexes': [models.Index(fields=['connection', 'status'], name='broker_orde_connect_c2978a_idx'), models.Index(fields=['connection', 'symbol'], name='broker_orde_connect_e944fc_idx'), models.Index(fields=['connection', 'submitted_at'], name='broker_orde_connect_fe99e8_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='brokerconnection',
            index=models.Index(fields=['user', 'broker'], name='broker_conn_user_id_aa3703_idx'),
        ),
        migrations.AddIndex(
            model_name='brokerconnection',
            index=models.Index(fields=['user', 'status'], name='broker_conn_user_id_bf3138_idx'),
        ),
        migrations.AddIndex(
            model_name='brokerconnection',
            index=models.Index(fields=['broker', 'status'], name='broker_conn_broker_7a744a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='brokerconnection',
            unique_together={('user', 'broker', 'account_id')},
        ),
    ]
