# Generated by Django 4.2.27 on 2025-12-28 11:18

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0009_dataprovider_priority'),
        ('assets', '0004_country_exchange'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetMetricsHistoric',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('market_cap', models.DecimalField(decimal_places=2, max_digits=30, null=True)),
                ('fdv', models.DecimalField(decimal_places=2, max_digits=30, null=True)),
                ('circulating_supply', models.DecimalField(decimal_places=8, max_digits=30, null=True)),
                ('total_supply', models.DecimalField(decimal_places=8, max_digits=30, null=True)),
                ('max_supply', models.DecimalField(decimal_places=8, max_digits=30, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=10, max_digits=30, null=True)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=30, null=True)),
                ('price_change_1d', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('volume_change_1d', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('price_change_1d_pct', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('volume_change_1d_pct', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('price_change_7d', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('volume_change_7d', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('price_change_7d_pct', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('volume_change_7d_pct', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('price_change_30d', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('volume_change_30d', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('price_change_30d_pct', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('volume_change_30d_pct', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('price_change_90d', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('volume_change_90d', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('price_change_90d_pct', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('volume_change_90d_pct', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('price_change_180d', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('volume_change_180d', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('price_change_180d_pct', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('volume_change_180d_pct', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('price_change_1y', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('volume_change_1y', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('price_change_1y_pct', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('volume_change_1y_pct', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('ath_price_7d', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                ('ath_price_date_7d', models.DateField(null=True)),
                ('atl_price_7d', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                ('atl_price_date_7d', models.DateField(null=True)),
                ('ath_price_30d', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                ('ath_price_date_30d', models.DateField(null=True)),
                ('atl_price_30d', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                ('atl_price_date_30d', models.DateField(null=True)),
                ('ath_price_90d', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                ('ath_price_date_90d', models.DateField(null=True)),
                ('atl_price_90d', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                ('atl_price_date_90d', models.DateField(null=True)),
                ('ath_price_180d', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                ('ath_price_date_180d', models.DateField(null=True)),
                ('atl_price_180d', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                ('atl_price_date_180d', models.DateField(null=True)),
                ('ath_price_1y', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                ('ath_price_date_1y', models.DateField(null=True)),
                ('atl_price_1y', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                ('atl_price_date_1y', models.DateField(null=True)),
            ],
            options={
                'db_table': 'asset_metrics_historic',
            },
        ),
        migrations.CreateModel(
            name='AssetPricesHistoric',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('open', models.DecimalField(decimal_places=8, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('1E-8'))])),
                ('high', models.DecimalField(decimal_places=8, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('1E-8'))])),
                ('low', models.DecimalField(decimal_places=8, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('1E-8'))])),
                ('close', models.DecimalField(decimal_places=8, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('1E-8'))])),
                ('volume', models.BigIntegerField(blank=True, null=True)),
                ('volatility', models.DecimalField(blank=True, decimal_places=4, help_text='Calculated volatility (e.g., 30-day std dev)', max_digits=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'Prices Historic',
                'db_table': 'asset_prices_historic',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='AssetRecommendation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('analyst_firm', models.CharField(max_length=150)),
                ('rating', models.CharField(help_text='e.g. Overweight, Buy, Hold', max_length=50)),
                ('target_price', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('rating_date', models.DateField(db_index=True)),
                ('source_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'db_table': 'asset_recommendations',
            },
        ),
        migrations.CreateModel(
            name='AssetTopHolder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('holder_name', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=30)),
                ('percentage_owned', models.DecimalField(decimal_places=4, max_digits=7)),
                ('report_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'asset_top_holders',
            },
        ),
        migrations.CreateModel(
            name='CorporateAction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('split', 'Stock Split'), ('dividend', 'Dividend'), ('merger', 'Merger'), ('spinoff', 'Spinoff')], max_length=50)),
                ('execution_date', models.DateField(db_index=True)),
                ('ratio', models.DecimalField(blank=True, decimal_places=6, help_text='e.g. 4.0 for 4-for-1 split', max_digits=15, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=8, help_text='Dividend amount per share', max_digits=20, null=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'asset_corporate_actions_1',
                'ordering': ['-execution_date'],
            },
        ),
        migrations.CreateModel(
            name='CryptoAsset',
            fields=[
                ('asset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assets.asset')),
                ('circulating_supply', models.DecimalField(decimal_places=10, max_digits=40, null=True)),
                ('total_supply', models.DecimalField(decimal_places=10, max_digits=40, null=True)),
                ('max_supply', models.DecimalField(decimal_places=10, max_digits=40, null=True)),
                ('fdv', models.DecimalField(decimal_places=2, help_text='Fully Diluted Valuation', max_digits=30, null=True)),
                ('contract_address', models.CharField(blank=True, max_length=255, null=True)),
                ('blockchain', models.CharField(blank=True, max_length=255, null=True)),
                ('tvl', models.DecimalField(decimal_places=10, max_digits=40, null=True)),
            ],
            options={
                'db_table': 'assets_crypto',
            },
            bases=('assets.asset',),
        ),
        migrations.CreateModel(
            name='ETFAsset',
            fields=[
                ('asset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assets.asset')),
                ('expense_ratio', models.DecimalField(decimal_places=4, max_digits=5, null=True)),
                ('aum', models.DecimalField(decimal_places=2, max_digits=30, null=True)),
            ],
            options={
                'db_table': 'asset_etf',
            },
            bases=('assets.asset',),
        ),
        migrations.CreateModel(
            name='IndexAsset',
            fields=[
                ('asset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assets.asset')),
                ('constituents_count', models.IntegerField(null=True)),
                ('weighting_method', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'db_table': 'asset_indexes',
            },
            bases=('assets.asset',),
        ),
        migrations.AlterUniqueTogether(
            name='pricehistory',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='pricehistory',
            name='asset',
        ),
        migrations.RemoveIndex(
            model_name='asset',
            name='assets_asse_ticker_22a21f_idx',
        ),
        migrations.RemoveIndex(
            model_name='asset',
            name='assets_asse_asset_t_22f697_idx',
        ),
        migrations.RemoveIndex(
            model_name='asset',
            name='assets_asse_currenc_77fc2a_idx',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='cusip',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='isin',
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_class',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='assets.assetclass'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asset',
            name='ath_price',
            field=models.DecimalField(decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='ath_price_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='ath_volume',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='ath_volume_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='atl_price',
            field=models.DecimalField(decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='atl_price_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='atl_volume',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='atl_volume_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='exchanges',
            field=models.ManyToManyField(blank=True, related_name='assets', to='assets.exchange'),
        ),
        migrations.AddField(
            model_name='asset',
            name='market_cap',
            field=models.DecimalField(decimal_places=2, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='price_change_24h',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='price_change_24h_pct',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='volume_24h',
            field=models.DecimalField(decimal_places=2, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.country'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['status', 'ticker'], name='assets_status_097f43_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['asset_type', 'market_cap'], name='assets_asset_t_619b53_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['last_price_updated_at'], name='assets_last_pr_aa1f3b_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['last_price'], name='assets_last_pr_be7561_idx'),
        ),
        migrations.AlterModelTable(
            name='asset',
            table='assets',
        ),
        migrations.CreateModel(
            name='StockAsset',
            fields=[
                ('asset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assets.asset')),
                ('industry', models.CharField(blank=True, max_length=150)),
                ('sector', models.CharField(blank=True, max_length=150)),
                ('isin', models.CharField(blank=True, help_text='International Securities Identification Number', max_length=12)),
                ('cusip', models.CharField(blank=True, max_length=9, null=True)),
                ('pe_ratio', models.DecimalField(decimal_places=4, max_digits=12, null=True)),
                ('dividend_yield', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('eps', models.DecimalField(decimal_places=4, max_digits=15, null=True)),
                ('revenue_ttm', models.DecimalField(decimal_places=2, max_digits=30, null=True)),
            ],
            options={
                'db_table': 'assets_stocks',
            },
            bases=('assets.asset',),
        ),
        migrations.DeleteModel(
            name='PriceHistory',
        ),
        migrations.AddField(
            model_name='corporateaction',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corporate_actions_1', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='assettopholder',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='major_holders', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='assetrecommendation',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyst_ratings', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='assetpriceshistoric',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='assetpriceshistoric',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='investments.dataprovider'),
        ),
        migrations.AddField(
            model_name='assetmetricshistoric',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics_historic', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='assetmetricshistoric',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metrics_historic', to='investments.dataprovider'),
        ),
        migrations.AlterUniqueTogether(
            name='assettopholder',
            unique_together={('asset', 'holder_name', 'report_date')},
        ),
        migrations.AddIndex(
            model_name='assetpriceshistoric',
            index=models.Index(fields=['asset', '-date'], name='asset_price_asset_i_b9a2d3_idx'),
        ),
        migrations.AddIndex(
            model_name='assetpriceshistoric',
            index=models.Index(fields=['date'], name='asset_price_date_7f454a_idx'),
        ),
        migrations.AddIndex(
            model_name='assetpriceshistoric',
            index=models.Index(fields=['source'], name='asset_price_source__6fb62b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='assetpriceshistoric',
            unique_together={('asset', 'date', 'source')},
        ),
        migrations.AddIndex(
            model_name='assetmetricshistoric',
            index=models.Index(fields=['asset', '-date', 'source'], name='asset_metri_asset_i_888032_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='assetmetricshistoric',
            unique_together={('asset', 'date', 'source')},
        ),
    ]
