"""
Analytics Constants
Centralized configuration for financial analytics calculations.
Following best practices to avoid magic numbers.
"""

from datetime import timedelta

# Trading calendar
TRADING_DAYS_PER_YEAR = 252
TRADING_DAYS_PER_WEEK = 5
TRADING_DAYS_PER_MONTH = 21

# Performance metrics
DEFAULT_PERIOD = "1y"
MAX_PERIOD = "5y"
MIN_PERIOD = "1d"

# Risk metrics
DEFAULT_CONFIDENCE_LEVEL = 0.95
HIGH_CONFIDENCE_LEVEL = 0.99
VAR_CONFIDENCE_LEVELS = [0.90, 0.95, 0.99]

# Risk-free rate
DEFAULT_RISK_FREE_RATE = 0.05
RISK_FREE_RATE_SOURCE = "10y Treasury"

# Volatility
DEFAULT_VOLATILITY_WINDOW = 30
MAX_VOLATILITY_WINDOW = 252
MIN_VOLATILITY_WINDOW = 5

# Drawdown analysis
DRAWDOWN_HISTORY_BINS = 20

# Correlation analysis
CORRELATION_CLUSTER_THRESHOLD = 0.5
CORRELATION_MIN_OBSERVATIONS = 30
CORRELATION_METHOD = "pearson"

# Diversification
DIVERSIFICATION_EXCELLENT = 70
DIVERSIFICATION_MODERATE = 40
DIVERSIFICATION_POOR = 20

# Factor analysis
FACTOR_MARKET = "market"
FACTOR_SIZE = "size"
FACTOR_VALUE = "value"
FACTOR_MOMENTUM = "momentum"
FACTOR_LOW_VOL = "low_vol"

DEFAULT_FACTORS = [FACTOR_MARKET, FACTOR_SIZE, FACTOR_VALUE, FACTOR_MOMENTUM]

# Options
DEFAULT_OPTION_EXPIRATION_MONTHS = [1, 2, 3, 6, 12]
MAX_STRIKES_FOR_CHAIN = 50
MIN_OPTION_DAYS_TO_EXPIRY = 1
MAX_OPTION_DAYS_TO_EXPIRY = 730

# Greeks calculation
GREEKS_NUMERICAL_DELTA = 0.01
GREEKS_NUMERICAL_GAMMA = 0.01
GREEKS_NUMERICAL_VEGA = 0.01
GREEKS_NUMERICAL_THETA = 1 / 365
GREEKS_NUMERICAL_RHO = 0.01

# Monte Carlo simulation
MONTE_CARLO_SIMULATIONS = 10000
MONTE_CARLO_SEED = 42

# Chart data limits
MAX_CHART_POINTS = 500
HISTOGRAM_BINS = 20
DISTRIBUTION_TAIL_BINS = 10

# Cache TTL (seconds)
ANALYTICS_CACHE_TTL_SHORT = 60
ANALYTICS_CACHE_TTL_MEDIUM = 300
ANALYTICS_CACHE_TTL_LONG = 3600

# API response limits
MAX_ASSETS_IN_CORRELATION = 50
MAX_FACTORS_IN_ANALYSIS = 10

# Interpretation thresholds
VOLATILITY_LOW = 0.15
VOLATILITY_MODERATE = 0.30
VOLATILITY_HIGH = 0.50

SHARPE_EXCELLENT = 1.5
SHARPE_GOOD = 1.0
SHARPE_ACCEPTABLE = 0.5
SHARPE_POOR = 0.0

MAX_DRAWDOWN_MINOR = 0.05
MAX_DRAWDOWN_MODERATE = 0.15
MAX_DRAWDOWN_MAJOR = 0.30

# Error codes
ERROR_INSUFFICIENT_DATA = "insufficient_data"
ERROR_INVALID_INPUT = "invalid_input"
ERROR_CALCULATION_FAILED = "calculation_failed"
